import {registerAndLogin} from './player-account.mjs';
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
const url=process.env.AINCRAD_URL||'http://127.0.0.1:8080',password=process.env.AINCRAD_ADMIN_PASSWORD;
if(!password)throw Error('Usa un servidor aislado y AINCRAD_ADMIN_PASSWORD.');
const out=new URL('../../docs/screenshots/',import.meta.url).pathname;
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']});
const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),admin=await context.newPage(),errors=[],checks=[];let state;
for(const p of [page,admin]){p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&!m.text().startsWith('WebSocket connection'))errors.push(m.text());});}
page.on('websocket',ws=>ws.on('framereceived',({payload})=>{try{const m=JSON.parse(String(payload));if(m.type==='state')state=m;}catch{}}));
const me=()=>state?.players.find(p=>p.id===state.you);
const wait=async(fn,message)=>{const end=Date.now()+30000;while(Date.now()<end){if(fn())return;await new Promise(r=>setTimeout(r,100));}throw Error(message);};
const done=s=>{checks.push(s);console.log(s);};
try{
 await registerAndLogin(context.request,url);
 await page.bringToFront();await page.goto(url);await page.getByRole('button',{name:'Chica',exact:true}).click();await page.getByLabel('Raza',{exact:true}).selectOption('elf');await page.getByLabel('Clase',{exact:true}).selectOption('healer');await page.getByLabel('Rostro',{exact:true}).selectOption('kind');
 await page.getByRole('button',{name:'Acercar al rostro',exact:true}).click();const stage=page.locator('.avatar-stage');await stage.scrollIntoViewIfNeeded();await page.waitForTimeout(350);await stage.screenshot({path:out+'15-editor-rostro.png'});await page.getByRole('button',{name:'Ver cuerpo entero',exact:true}).click();const canvas=stage.locator('canvas'),box=await canvas.boundingBox();await page.mouse.move(box.x+box.width*.4,box.y+box.height*.5);await page.mouse.down();await page.mouse.move(box.x+box.width*.6,box.y+box.height*.5,{steps:5});await page.mouse.up();await page.waitForTimeout(250);await stage.screenshot({path:out+'16-editor-cuerpo.png'});done('Angular crea una elfa sanadora y permite primer plano, cuerpo entero y giro con ratón');
 await page.getByLabel('TU NOMBRE DE AVENTURERO').fill('Nerea');await page.getByRole('button',{name:/Entrar al mundo/}).click();await wait(()=>me(),'No entró el personaje');assert.equal(me().appearance.race,'elf');assert.equal(me().appearance.classId,'healer');
 const worldCanvas=page.locator('#world-canvas');await worldCanvas.focus();const start=me().z;await page.keyboard.down('KeyW');await page.waitForTimeout(350);await page.keyboard.up('KeyW');await wait(()=>me().z<start-.7,'No se mueve el modelo nuevo');await page.keyboard.press('KeyE');await page.locator('.dialogue').waitFor();assert.ok((await page.locator('.dialogue').innerText()).includes('Lyra'));await page.getByRole('button',{name:'Continuar →',exact:true}).click();await page.screenshot({path:out+'17-personajes-mundo.png'});done('Modelo en el mundo, movimiento y conversación con Lyra funcionan con el servidor real');
 await page.getByRole('button',{name:'Editar mi personaje',exact:true}).click();const editor=page.locator('.drawer character-editor');await editor.getByRole('button',{name:'Chico',exact:true}).click();await editor.getByLabel('Raza',{exact:true}).selectOption('darkelf');await page.getByRole('button',{name:'Guardar personaje',exact:true}).click();await wait(()=>me().appearance.gender==='male'&&me().appearance.race==='darkelf','Autoedición no aplicada');await page.getByRole('button',{name:'Cerrar panel',exact:true}).click();done('Autoedición de raza y género se propaga al personaje conectado');
 await page.goto('about:blank');console.log('Escena del juego cerrada antes de abrir root');await admin.bringToFront();await admin.goto(url+'/admin');await admin.getByLabel('Contraseña',{exact:true}).fill(password);await admin.getByRole('button',{name:/Entrar como root/}).click();console.log('Login enviado');await admin.getByRole('heading',{name:'Construye el siguiente nivel.'}).waitFor({timeout:60000});console.log('Panel root visible');await admin.getByRole('button',{name:'Actualizar lista',exact:true}).click();await admin.locator('.character-list').getByRole('button',{name:/Nerea/}).click();const rootEditor=admin.locator('.admin-character-editor');await rootEditor.getByLabel('Raza',{exact:true}).selectOption('draconian');await rootEditor.getByLabel('Clase',{exact:true}).selectOption('warrior');await rootEditor.getByLabel('Especialidad',{exact:true}).selectOption('tank');await rootEditor.getByRole('button',{name:'Chica',exact:true}).click();await admin.getByLabel('EXP total (0–100000)').fill('2000');await rootEditor.getByRole('button',{name:'Guardar personaje',exact:true}).click();await admin.getByText(/Personaje actualizado. Se guardó una copia anterior y el cambio es visible en el juego./).waitFor();await rootEditor.getByRole('button',{name:'Acercar al rostro',exact:true}).click();await rootEditor.locator('.avatar-stage').scrollIntoViewIfNeeded();await admin.waitForTimeout(300);await admin.screenshot({path:out+'18-personaje-root.png'});done('Root modifica raza, género, clase, especialidad y nivel del perfil guardado');
 const gear=admin.locator('.equipment-editor');await gear.getByRole('button',{name:'Duplicar conjunto',exact:true}).click();await gear.getByLabel('Tela',{exact:true}).fill('#cb2f67');await gear.getByLabel('Metal',{exact:true}).fill('#3c98c3');await gear.getByLabel('Casco',{exact:true}).check();await gear.getByRole('button',{name:'Ver cuerpo entero',exact:true}).click();await gear.locator('.avatar-stage').scrollIntoViewIfNeeded();await admin.waitForTimeout(250);await gear.locator('.avatar-stage').screenshot({path:out+'19-equipo-root.png'});await gear.getByRole('button',{name:'Eliminar conjunto',exact:true}).click();done('Vista root representa el conjunto seleccionado, incluidos colores y casco antes de guardarlo');
 await admin.goto('about:blank');await page.bringToFront();state=null;await page.goto(url);await page.getByRole('button',{name:/Continuar aventura/}).click();await wait(()=>me()?.appearance.race==='draconian','No se recuperó el personaje');assert.equal(me().appearance.specializationId,'tank');assert.equal(me().appearance.gender,'female');assert.ok(me().level>1);done('Recargar conserva la identidad, el nivel y el equipo compatible');
 assert.deepEqual(errors,[]);await writeFile(new URL('../../docs/avatar-browser-result.json',import.meta.url),JSON.stringify({date:new Date().toISOString(),browser:browser.version(),checks,errors},null,2)+'\n');
}catch(e){await page.screenshot({path:out+'failure-avatar-game.png'}).catch(()=>{});await admin.screenshot({path:out+'failure-avatar-admin.png'}).catch(()=>{});console.error({message:e.message,errors,me:me()&&{race:me().appearance,level:me().level},admin:await admin.locator('body').innerText().then(t=>t.slice(-500)).catch(()=>'' )});throw e;}finally{await browser.close();}
