// Source-level visual and WebGL lifecycle verification; serves only the three local
// directories needed by the harness and binds to loopback on an ephemeral port.
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import http from 'node:http';
import path from 'node:path';
const root=new URL('../../',import.meta.url).pathname,out=root+'docs/screenshots';await mkdir(out,{recursive:true});
const html=`<!doctype html><meta charset="utf-8"><link rel="icon" href="data:,"><style>html,body{margin:0;background:radial-gradient(ellipse at 35% 25%,#d2dbc9,#849b8e);font-family:system-ui;color:#203e39}canvas{width:600px;height:720px;display:block}header{position:absolute;top:24px;left:28px}small{font-size:10px;letter-spacing:.18em}h1{font:28px Georgia;margin:7px 0}</style><header><small>AINCRAD · PERSONAJES 3D</small><h1 id="title">Humano</h1></header><canvas id="c" tabindex="0"></canvas><script type="importmap">{"imports":{"three":"/client/node_modules/three/build/three.module.js","three/addons/":"/client/node_modules/three/examples/jsm/"}}</script><script type="module">import {AvatarPreview} from '/client/src/app/world-renderer.js';import {npcAppearance} from '/client/src/app/avatar-model.js';window.npcAppearance=npcAppearance;window.catalog=(await(await fetch('/world/world.json')).json()).characterOptions;window.look={gender:'female',race:'human',face:'kind',classId:'warrior',specializationId:'swordsman',skinColor:'#dfb18b',hairColor:'#74503a'};window.view='body';window.level=1;window.resolved=null;window.preview=new AvatarPreview(document.querySelector('canvas'),()=>look,()=>catalog,()=>level,()=>'',()=>view,()=>resolved);preview.renderer.setAnimationLoop(null);window.ready=true;</script>`;
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname==='/inspect'){res.setHeader('Content-Type','text/html');return res.end(html);}const f=path.resolve(root,'.'+decodeURIComponent(u.pathname));if(!['client/src/','client/node_modules/three/','world/world.json'].some(p=>f.startsWith(root+p)))throw Error();res.setHeader('Content-Type',f.endsWith('.js')||f.endsWith('.mjs')?'text/javascript':'application/json');res.end(await readFile(f));}catch{res.statusCode=404;res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']});
const errors=[],checks=[],metrics=[];
try{
 const page=await browser.newPage({viewport:{width:600,height:720}});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.goto(`http://127.0.0.1:${server.address().port}/inspect`);await page.waitForFunction(()=>window.ready&&window.preview.visible&&document.hasFocus());
 const configs=[['human','female','warrior','swordsman',5],['human','male','warrior','assassin',1],['dwarf','male','warrior','tank',10],['dwarf','female','warrior','swordsman',1],['elf','female','healer','healer',5],['elf','male','mage','earth',1],['darkelf','male','mage','fire',10],['darkelf','female','warrior','assassin',5],['draconian','female','warrior','tank',5],['draconian','male','healer','healer',1]];
 for(const [race,gender,classId,specializationId,level] of configs){const result=await page.evaluate(({race,gender,classId,specializationId,level})=>{const r=catalog.races.find(x=>x.id===race);window.look={race,gender,classId,specializationId,face:gender==='female'?'kind':'bold',skinColor:r.skinColors[0],hairColor:r.hairColors[0]};window.level=level;view='body';document.querySelector('h1').textContent=r.name+' · '+(gender==='female'?'Chica':'Chico');preview.lastFrame=0;preview.renderFrame();return {race,gender,triangles:preview.renderer.info.render.triangles,drawCalls:preview.renderer.info.render.calls,memory:{...preview.renderer.info.memory},error:preview.renderer.getContext().getError()};},{race,gender,classId,specializationId,level});assert.equal(result.error,0);assert.ok(result.drawCalls>0);metrics.push(result);await page.screenshot({path:out+'/avatar-'+race+'-'+gender+'.png'});console.log('Vista verificada: '+race+' '+gender);}
 checks.push('Diez combinaciones de cinco razas y dos géneros, tres clases y niveles 1/5/10, sin errores WebGL');
 await page.evaluate(()=>{const style=npcAppearance({role:'guide'});look=style.appearance;resolved=style;view='face';document.querySelector('h1').textContent='Lyra · guía del refugio';preview.lastFrame=0;preview.renderFrame();});await page.screenshot({path:out+'/avatar-lyra.png'});checks.push('Lyra usa pelo corto, capa verde, armadura y libro propios en el mismo renderizador');
 const lifecycle=await page.evaluate(()=>{resolved=null;view='face';look={gender:'female',race:'elf',face:'kind',classId:'healer',specializationId:'healer',skinColor:'#dfb18b',hairColor:'#e8dec2'};preview.lastFrame=0;preview.renderFrame();const start={...preview.renderer.info.memory};for(let i=0;i<12;i++){look.hairColor=i%2?'#e8dec2':'#342f32';preview.lastFrame=0;preview.renderFrame();}return {start,end:{...preview.renderer.info.memory},error:preview.renderer.getContext().getError()};});assert.equal(lifecycle.start.geometries,lifecycle.end.geometries);assert.equal(lifecycle.start.textures,lifecycle.end.textures);assert.equal(lifecycle.error,0);checks.push('Doce cambios de aspecto no aumentan las geometrías ni texturas residentes');
 await page.evaluate(()=>{document.querySelector('h1').textContent='Elfa · detalle del rostro';preview.angle=.38;preview.lastFrame=0;preview.renderFrame();});await page.screenshot({path:out+'/avatar-elf-portrait.png'});
 const rotation=await page.evaluate(()=>preview.angle);await page.locator('canvas').focus();await page.keyboard.press('ArrowRight');await page.evaluate(()=>{preview.lastFrame=0;preview.renderFrame();});assert.ok(await page.evaluate(()=>preview.angle)>rotation);
 await page.setViewportSize({width:320,height:640});await page.addStyleTag({content:'canvas{width:320px;height:640px}'});await page.waitForTimeout(200);await page.evaluate(()=>{preview.lastFrame=0;preview.renderFrame();});await page.screenshot({path:out+'/avatar-mobile-portrait.png'});checks.push('Giro con teclado y encuadre de rostro en canvas estrecho');
 await page.evaluate(()=>preview.dispose());assert.deepEqual(errors,[]);
 await writeFile(root+'docs/avatar-visual-result.json',JSON.stringify({date:new Date().toISOString(),browser:browser.version(),checks,metrics,lifecycle,errors},null,2)+'\n');console.log(checks);
}finally{await browser.close();server.close();}
