import {registerAndLogin} from './player-account.mjs';
import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
const url=process.env.AINCRAD_URL||'http://127.0.0.1:8080';
const password=process.env.AINCRAD_ADMIN_PASSWORD;
if(!password)throw new Error('Configura AINCRAD_ADMIN_PASSWORD para un servidor de pruebas aislado.');
const output=new URL('../../docs/screenshots/',import.meta.url).pathname;await mkdir(output,{recursive:true});
let launch={headless:true,executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']};
if(process.env.CHROMIUM_MODULE){const {default:c}=await import(pathToFileURL(process.env.CHROMIUM_MODULE));launch.executablePath=await c.executablePath();launch.args=[...c.args,'--enable-unsafe-swiftshader'];}
const browser=await chromium.launch(launch);
const errors=[];let a,b,admin,panel,first,second,lastState,otherState;const checks=[];const push=checks.push.bind(checks);checks.push=(...items)=>{console.log(items.join('; '));return push(...items);};
const wait=async(fn,msg,ms=20000)=>{const end=Date.now()+ms;while(Date.now()<end){if(fn())return;await new Promise(r=>setTimeout(r,80));}throw new Error(msg);};
const record=(page,set)=>{page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')console.error('Browser: '+m.text());});page.on('websocket',ws=>ws.on('socketerror',e=>console.error('WebSocket: '+e)));page.on('websocket',ws=>ws.on('framereceived',({payload})=>{try{const n=JSON.parse(String(payload));if(n.type==='state')set(n);}catch{}}));};
try{
 a=await browser.newContext({viewport:{width:1440,height:1000}});first=await a.newPage();record(first,s=>lastState=s);
 await registerAndLogin(a.request,url);await first.goto(url);await first.getByRole('heading',{name:'El cielo no es el límite.'}).waitFor();
 await first.getByRole('button',{name:'Chica',exact:true}).click();await first.getByLabel('Raza',{exact:true}).selectOption('elf');await first.getByLabel('Clase',{exact:true}).selectOption('mage');await first.getByLabel('Rostro',{exact:true}).selectOption('kind');await first.getByRole('button',{name:'Cabello #c39757',exact:true}).click();await first.getByLabel('TU NOMBRE DE AVENTURERO').fill('Astra');
 await first.waitForTimeout(400);assert.equal(await first.locator('img').evaluateAll(imgs=>imgs.every(i=>i.complete&&i.naturalWidth>0)),true);
 assert.equal(await first.locator('.creation-panel').evaluate(el=>getComputedStyle(el).position),'absolute');await first.screenshot({path:output+'01-creacion.png'});checks.push('Creación de personaje, vista previa WebGL y estilos');
 await first.getByRole('button',{name:/Entrar al mundo/}).click();await wait(()=>lastState?.players?.length,'El personaje no entró');let me=()=>lastState.players.find(p=>p.id===lastState.you);assert.equal(me().appearance.gender,'female');assert.equal(me().appearance.race,'elf');assert.equal(me().appearance.classId,'mage');assert.equal(me().maxHp,85);assert.equal(me().speed,5.6);
 const initialZ=me().z;await first.locator('#world-canvas').focus();await first.keyboard.down('KeyW');await first.waitForTimeout(340);await first.keyboard.up('KeyW');await first.waitForTimeout(350);assert.ok(me().z<initialZ-.7&&me().z>initialZ-3.5);checks.push('Movimiento W correcto, a velocidad de la clase');
 await first.keyboard.press('KeyE');await first.locator('.dialogue').waitFor();await wait(()=>me().quest,'La misión no llegó en la instantánea');await first.getByRole('button',{name:'Continuar →',exact:true}).click();
 b=await browser.newContext({viewport:{width:1280,height:900}});second=await b.newPage();record(second,s=>otherState=s);await registerAndLogin(b.request,url);await second.goto(url);await second.getByLabel('TU NOMBRE DE AVENTURERO').fill('Compañero');await second.getByRole('button',{name:/Entrar al mundo/}).click();await wait(()=>otherState?.players?.length===2&&lastState?.players?.length===2,'No se ven dos jugadores');assert.equal(otherState.players.find(p=>p.id===lastState.you).appearance.race,'elf');checks.push('Dos sesiones reales comparten posición y aspecto');
 await first.getByLabel('Mensaje de chat').fill('Hola desde Aincrad');await first.getByRole('button',{name:'Enviar mensaje',exact:true}).click();await second.getByText('Hola desde Aincrad',{exact:false}).waitFor();checks.push('Chat del piso entre navegadores');await b.close();b=null;second=undefined;
 await first.getByRole('button',{name:'Editar mi personaje',exact:true}).click();await first.locator('.drawer').getByRole('button',{name:'Chico',exact:true}).click();await first.getByRole('button',{name:'Guardar personaje',exact:true}).click();await wait(()=>me().appearance.gender==='male','No se guardó la autoedición en refugio');assert.equal(me().xp,0);await first.getByRole('button',{name:'Cerrar panel',exact:true}).click();checks.push('Autoedición autorizada del propio personaje sin alterar progreso');
 await first.screenshot({path:output+'02-mundo.png'});
 admin=await browser.newContext({viewport:{width:1500,height:1000}});panel=await admin.newPage();panel.on('pageerror',e=>errors.push(e.message));await panel.goto(url+'/admin');await panel.getByLabel('Contraseña',{exact:true}).fill(password);await panel.getByRole('button',{name:'Entrar como root',exact:false}).click();await panel.getByRole('heading',{name:'Construye el siguiente nivel.'}).waitFor();
 await panel.getByRole('button',{name:'Actualizar lista',exact:true}).click();await panel.locator('.character-list').getByRole('button',{name:/Astra/}).click();await panel.getByLabel('Col (0–10000000)').fill('77');await panel.getByRole('button',{name:'Guardar personaje',exact:true}).click();await wait(()=>me().col===77,'La edición root no se propagó');checks.push('Root edita personajes, cliente recibe cambio en vivo');
 await panel.getByLabel('EXP total (0–100000)').fill('200');await panel.getByRole('button',{name:'Guardar personaje',exact:true}).click();await wait(()=>me().level===3,'Root no cambió el nivel');
 await first.getByRole('button',{name:'Atributos y talentos',exact:true}).click();await first.getByRole('button',{name:'Aumentar Vitalidad',exact:true}).click();await first.getByRole('button',{name:'Aprender Concentración',exact:true}).click();await first.getByRole('button',{name:'Aprender Flujo mágico',exact:true}).click();await first.getByRole('button',{name:'Guardar atributos y talentos',exact:true}).click();await wait(()=>me().attributeRanks.vitality===1&&me().talentRanks['mage-flow']===1,'No se guardó el árbol');assert.equal(me().attributePoints,5);assert.equal(me().talentPoints,0);assert.equal(me().maxHp,120);await first.screenshot({path:output+'06-talentos.png'});await first.getByRole('button',{name:'Cerrar panel',exact:true}).click();checks.push('Subida de nivel, puntos de atributo y árbol de mago guardados desde el personaje');
 await panel.getByRole('button',{name:/Añadir nuevo conjunto/}).click();await panel.locator('.equipment-editor').getByLabel('Nombre',{exact:true}).fill('Conjunto de prueba');await panel.locator('.equipment-editor').getByRole('button',{name:'Añadir atributo',exact:true}).click();await panel.getByLabel('Valor health',{exact:true}).fill('25');await panel.getByRole('button',{name:'Eliminar conjunto',exact:true}).click();checks.push('Root añade un conjunto y configura atributos variables');

 const nameInput=panel.getByLabel('Nombre del piso',{exact:true});const original=await nameInput.inputValue();await nameInput.fill('Praderas de prueba');await panel.getByRole('button',{name:'Guardar y validar',exact:true}).click();await panel.getByText(/Mundo validado y guardado/).waitFor();await panel.getByRole('button',{name:'Aplicar y reconectar',exact:false}).click();await first.getByRole('heading',{name:'Praderas de prueba',exact:true}).waitFor({timeout:40000});
 await panel.getByRole('button',{name:'Guardar y validar',exact:true}).waitFor();await panel.waitForFunction(()=>[...document.querySelectorAll('button')].find(b=>b.textContent.trim()==='Guardar y validar')?.disabled===false);await nameInput.fill(original);await panel.getByRole('button',{name:'Guardar y validar',exact:true}).click();await panel.getByText(/Mundo validado y guardado/).waitFor();await panel.getByRole('button',{name:'Aplicar y reconectar',exact:false}).click();await first.getByRole('heading',{name:original,exact:true}).waitFor({timeout:40000});checks.push('Edición del mundo, respaldo, aplicación y reconexión');
 await panel.screenshot({path:output+'03-admin.png'});await panel.getByRole('heading',{name:'Voces de Aincrad'}).scrollIntoViewIfNeeded();await panel.screenshot({path:output+'04-ollama.png'});await admin.close();admin=null;panel=undefined;
 await first.getByRole('button',{name:'Abrir diario',exact:true}).click();await first.locator('.journal-card img').last().waitFor();await first.waitForFunction(()=>[...document.querySelectorAll('.journal-card img')].every(i=>i.complete&&i.naturalWidth>0));assert.equal(await first.locator('.journal-card img').evaluateAll(imgs=>imgs.every(i=>i.complete&&i.naturalWidth>0)),true);await first.screenshot({path:output+'05-diario.png'});checks.push('Ilustraciones locales de personaje, criatura y árbol');
 lastState=null;await first.reload();await first.getByRole('button',{name:/Continuar aventura/}).click();await wait(()=>lastState?.players?.find(p=>p.id===lastState.you)?.attributeRanks?.vitality===1,'No se restauró el progreso');checks.push('Recarga recupera personaje, nivel y talentos');assert.deepEqual(errors,[]);const result={browser:browser.version(),checks,errors};await writeFile(new URL('../../docs/browser-result.json',import.meta.url),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
} catch(e){console.error(e.message);if(panel)await panel.screenshot({path:output+'failure-admin.png',timeout:5000}).catch(()=>{});console.error(JSON.stringify({lastState:lastState&&{you:lastState.you,players:lastState.players.map(p=>({name:p.name,id:p.id}))},otherState:otherState&&{you:otherState.you,players:otherState.players.map(p=>({name:p.name,id:p.id}))},errors}));if(second)await second.screenshot({path:output+'failure-second.png'}).catch(()=>{});if(first)await first.screenshot({path:output+'failure-game.png'}).catch(()=>{});throw e;}finally{await browser.close();}
