import {registerAndLogin} from './player-account.mjs';
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const url=process.env.AINCRAD_URL||'http://127.0.0.1:8080',password=process.env.AINCRAD_ADMIN_PASSWORD;
if(!password)throw new Error('Usa un servidor aislado con AINCRAD_ADMIN_PASSWORD.');
const output=new URL('../../docs/screenshots/',import.meta.url).pathname;await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']});
const ctx=await browser.newContext({viewport:{width:1440,height:1000}}),page=await ctx.newPage();let state;const errors=[],checks=[],notices=[];
page.on('pageerror',e=>errors.push(e.message));page.on('websocket',ws=>ws.on('framereceived',({payload})=>{try{const n=JSON.parse(String(payload));if(n.type==='state')state=n;else if(n.type==='notice'||n.type==='error')notices.push(n.text);}catch{}}));
await page.addInitScript(()=>{const Original=window.WebSocket;window.WebSocket=class extends Original{constructor(...args){super(...args);window.__testSocket=this;}};});
const me=()=>state?.players.find(p=>p.id===state.you);
const wait=async(fn,msg,ms=25000)=>{const end=Date.now()+ms;while(Date.now()<end){if(fn())return;await new Promise(r=>setTimeout(r,100));}throw new Error(msg);};
const done=s=>{checks.push(s);console.log(s);};
const send=async n=>page.evaluate(n=>window.__testSocket.send(JSON.stringify(n)),n);
const close=async()=>{const b=page.getByRole('button',{name:'Cerrar panel',exact:true});if(await b.count())await b.click();};
const api=async(path,method,data)=>{const r=await ctx.request.fetch(url+'/api/admin/'+path,{method,data,headers:{Origin:url,'X-Aincrad-Admin':'1'}});assert.ok(r.ok(),await r.text());return r.json();};
try{
 await registerAndLogin(ctx.request,url);
 await page.goto(url);await page.getByLabel('Raza',{exact:true}).selectOption('draconian');await page.getByLabel('Especialidad',{exact:true}).selectOption('tank');await page.getByLabel('TU NOMBRE DE AVENTURERO').fill('Forjador');await page.screenshot({path:output+'07-draconiano.png'});await page.getByRole('button',{name:/Entrar al mundo/}).click();await wait(()=>me(),'No entró el personaje');assert.equal(me().appearance.specializationId,'tank');assert.equal(me().weapons.offHand.kind,'shield');assert.equal(me().outfit.style,'plate');done('Draconiano tanque: armadura de placas, escudo y rasgos visibles');
 await api('login','POST',{username:'root',password});await api('characters/'+me().id,'PATCH',{name:me().name,appearance:me().appearance,xp:1000,col:600,potions:5});await wait(()=>me().level===11,'Root no concedió nivel');await api('characters/'+me().id+'/crafting','PATCH',{professionXp:me().crafting.professionXp,materials:{...me().crafting.materials,copper:2}});await wait(()=>me().crafting.materials.copper===2,'Root no concedió material de prueba');
 await page.getByRole('button',{name:'Editar mi personaje',exact:true}).click();await page.locator('.drawer').getByLabel('Clase',{exact:true}).selectOption('mage');await page.getByRole('button',{name:'Guardar personaje',exact:true}).click();await wait(()=>me().appearance.classId==='mage','No cambió la clase');await close();
 await page.getByRole('button',{name:'Abrir inventario',exact:true}).click();await page.locator('.weapon-inventory').getByRole('button',{name:/Canalizador dual.*Nv. 1$/}).first().click();await wait(()=>me().weaponSetId==='mage-canalizador-1','No cambió el conjunto');assert.equal(me().weapons.mainHand.hands,1);assert.equal(me().weapons.offHand.kind,'wand');await close();done('Cambio de clase y elección de báculo de una mano con vara secundaria');
 await page.getByRole('button',{name:'Oficios y talleres',exact:true}).click();await page.getByRole('button',{name:'Ir al taller',exact:true}).click();await wait(()=>Math.hypot(me().x+6,me().z-16)<.25,'No llegó a Brann');
 const recipe='Vara arcana del comienzo · Canalizador dual · Nv. 1';await page.getByRole('button',{name:'Crear '+recipe,exact:true}).click();await wait(()=>me().crafting.items.length===1,'No se creó la vara');await page.getByRole('button',{name:'Mejorar a +1',exact:true}).click();await wait(()=>me().crafting.items[0].upgrade===1,'No mejoró la vara');await page.getByRole('button',{name:'Secundaria',exact:true}).click();await wait(()=>me().crafting.equipped.offHand,'No equipó la vara');await page.screenshot({path:output+'08-herreria.png'});await page.getByRole('button',{name:'Desequipar secundaria',exact:true}).click();await wait(()=>!me().crafting.equipped.offHand,'No desequipó');await close();done('Herrería: receta, pago, mejora y equipo artesanal en secundaria');
 await page.getByRole('button',{name:'Tienda',exact:true}).click();await page.getByRole('button',{name:'Ir a la tienda',exact:true}).click();await wait(()=>Math.hypot(me().x-6,me().z-23)<.3,'No llegó a Tessa');const wood=me().crafting.materials.wood,col=me().col;await page.locator('.shop-products').getByRole('button',{name:/Pino/}).click();await wait(()=>me().crafting.materials.wood===wood+1,'No compró madera');assert.ok(me().col<col);await page.getByRole('button',{name:/Vender ·/}).click();await wait(()=>me().crafting.items.length===0,'No vendió la vara');await close();done('Tienda: compra de pino y venta de objeto desequipado');
 // Normal move intentions, routed around server-supplied props; no coordinates are forced.
 const world=await (await ctx.request.get(url+'/api/world')).json(),floor=world.floors[0];
 const walk=async(x,z)=>{await send({type:'move',x,z});await wait(()=>Math.hypot(me().x-x,me().z-z)<.3,'Ruta bloqueada hacia '+x+','+z,35000);};
 const route=async(x,z)=>{const grid=1,key=(x,z)=>x+','+z,start=[Math.round(me().x),Math.round(me().z)],end=[Math.round(x),Math.round(z)];const queue=[start],seen=new Set([key(...start)]),parent=new Map();const free=(x,z)=>Math.hypot(x,z)<floor.radius-1&&!floor.props.some(p=>Math.hypot(x-p.x,z-p.z)<p.radius+.7);let found=false;
  for(let i=0;i<queue.length;i++){const [a,b]=queue[i];if(a===end[0]&&b===end[1]){found=true;break;}for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){const n=[a+dx,b+dz],k=key(...n);if(!seen.has(k)&&free(...n)){seen.add(k);parent.set(k,[a,b]);queue.push(n);}}}assert.ok(found,'No existe ruta de prueba');let path=[end];while(key(...path.at(-1))!==key(...start))path.push(parent.get(key(...path.at(-1))));path.reverse();const corners=[];for(let i=1;i<path.length;i++){if(i===path.length-1||path[i+1][0]-path[i][0]!==path[i][0]-path[i-1][0]||path[i+1][1]-path[i][1]!==path[i][1]-path[i-1][1])corners.push(path[i]);}for(const p of corners)await walk(...p);};
 await route(-14,6);await page.getByRole('button',{name:'Oficios y talleres',exact:true}).click();await page.locator('.profession-tabs').getByRole('button',{name:/Minería/}).click();let node=page.locator('.gather-list article').filter({hasText:'Veta de cobre'});const before=me().crafting.materials.copper||0;await node.getByRole('button',{name:'Recolectar',exact:true}).click();await wait(()=>(me().crafting.materials.copper||0)>before,'No recogió cobre');assert.ok(me().crafting.professionXp.mining>0);await page.screenshot({path:output+'09-mineria.png'});await close();done('Minería: acercamiento físico, cobre, experiencia y agotamiento compartido');
 await route(0,21.8);await wait(()=>state.monsters.every(m=>m.training||Math.hypot(m.x-me().x,m.z-me().z)>=8),'Las criaturas aún no se retiraron del refugio');await page.getByRole('button',{name:'Atributos y talentos',exact:true}).click();for(const id of ['fire-bolt','fire-storm','summon-sprite']){const name=world.characterOptions.skills.find(s=>s.id===id).name;await page.getByRole('button',{name:'Aprender '+name,exact:true}).click();}await page.getByRole('button',{name:'Guardar atributos y talentos',exact:true}).click();await wait(()=>me().skills.learned.includes('fire-storm'),'No aprendió las habilidades');await page.screenshot({path:output+'10-especialidades.png'});await close();done('Rama de fuego e invocación desbloqueadas mediante talentos');
 await page.getByRole('button',{name:'Entrenamiento',exact:true}).click();await page.getByRole('button',{name:'Ir al patio',exact:true}).click();await wait(()=>Math.hypot(me().x,me().z-27)<.25,'No llegó al patio');await page.locator('training-panel').getByRole('button',{name:/Muñeco de paja/}).click();const xp=me().xp;await page.locator('#world-canvas').focus();await page.keyboard.press('Digit2');await wait(()=>me().training.hits>=3,'No golpeó los tres muñecos con el área');await page.keyboard.press('Digit3');await wait(()=>state.summons.length===1&&me().training.hits>3,'No apareció la invocación');assert.equal(me().xp,xp);assert.equal(me().pvp.citizenship,100);await page.screenshot({path:output+'11-entrenamiento.png'});await page.locator('training-panel').getByRole('button',{name:/Aliado de prácticas/}).click();await wait(()=>me().target==='dummy-ally','No cambió al aliado');await page.getByRole('button',{name:'Reiniciar contadores',exact:true}).click();await wait(()=>me().training.hits===0,'No reinició contadores');done('Patio: daño en área, invocación, DPS y reinicio sin EXP ni sanción');
 await close();await route(0,16);const saved=me().talentRanks;state=null;await page.reload();await page.getByRole('button',{name:/Continuar aventura/}).click();await wait(()=>me()?.skills.learned.includes('summon-sprite'),'No persistieron las habilidades');assert.deepEqual(me().talentRanks,saved);assert.ok(me().crafting.professionXp.mining>0);assert.deepEqual(errors,[]);done('Recarga conserva especialidad, talentos y experiencia de minería');
 await writeFile(new URL('../../docs/expansion-browser-result.json',import.meta.url),JSON.stringify({browser:browser.version(),checks,errors},null,2)+'\n');
}catch(e){await page.screenshot({path:output+'failure-expansion.png'}).catch(()=>{});console.error({error:e.message,position:me()&&{x:me().x,z:me().z},errors,notices:notices.slice(-5)});throw e;}finally{await browser.close();}
