import {registerAndLogin} from './player-account.mjs';
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';

const url=process.env.AINCRAD_URL||'http://127.0.0.1:8080',rootPassword=process.env.AINCRAD_ADMIN_PASSWORD;
if(!rootPassword)throw Error('Usa un servidor aislado y AINCRAD_ADMIN_PASSWORD.');
const out=new URL('../../docs/screenshots/',import.meta.url).pathname;await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']});
const ctx=await browser.newContext({viewport:{width:1365,height:960}}),page=await ctx.newPage();page.setDefaultTimeout(60000);
const errors=[],checks=[],done=text=>{checks.push(text);console.log(text);};let state;
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().startsWith('WebSocket connection'))errors.push(m.text());});page.on('websocket',ws=>ws.on('framereceived',({payload})=>{try{const m=JSON.parse(String(payload));if(m.type==='state')state=m;}catch{}}));
const me=()=>state?.players.find(p=>p.id===state.you);
const wait=async(fn,message)=>{const end=Date.now()+60000;while(Date.now()<end){if(fn())return;await new Promise(r=>setTimeout(r,100));}throw Error(message);};
const headers={Origin:url,'X-Aincrad-Admin':'1'};
const admin=async(path,method='GET',data)=>{const r=await ctx.request.fetch(url+'/api/admin/'+path,{method,headers,data});assert.ok(r.ok(),await r.text());return r.json();};
try{
 await admin('login','POST',{username:'root',password:rootPassword});const draft=await admin('world');assert.equal(draft.crafting.shopProducts.length,28);
 // Only this disposable world uses cheap equipment, so actual gathered resources finance purchases.
 for(const p of draft.crafting.shopProducts)p.price=2;draft.crafting.materials.find(m=>m.id==='copper').sellPrice=2;await admin('world','PUT',draft);await admin('reload','POST',{});
 const world=await(await ctx.request.get(url+'/api/world')).json(),floor=world.floors[0];
 await registerAndLogin(ctx.request,url);
 await page.addInitScript(()=>{const Original=window.WebSocket;window.WebSocket=class extends Original{constructor(...args){super(...args);window.testGameSocket=this;}};});
 await page.goto(url);await page.getByRole('button',{name:'Chica',exact:true}).click();await page.getByLabel('TU NOMBRE DE AVENTURERO').fill('Mercadera');await page.getByRole('button',{name:/Entrar al mundo/}).click();await wait(()=>me()?.name==='Mercadera','No entra el personaje');const id=me().id;
 const send=message=>page.evaluate(m=>window.testGameSocket.send(JSON.stringify(m)),message);
 const walk=async(x,z)=>{await send({type:'move',x,z});await wait(()=>Math.hypot(me().x-x,me().z-z)<.3,'Ruta bloqueada hacia '+x+','+z);};
 const route=async(x,z)=>{const key=(x,z)=>x+','+z,start=[Math.round(me().x),Math.round(me().z)],end=[Math.round(x),Math.round(z)],queue=[start],seen=new Set([key(...start)]),parents=new Map();const free=(x,z)=>Math.hypot(x,z)<floor.radius-1&&!floor.props.some(p=>Math.hypot(x-p.x,z-p.z)<p.radius+.7);let found=false;
  for(let i=0;i<queue.length;i++){const [a,b]=queue[i];if(a===end[0]&&b===end[1]){found=true;break;}for(const [dx,dz]of[[1,0],[-1,0],[0,1],[0,-1]]){const n=[a+dx,b+dz],k=key(...n);if(!seen.has(k)&&free(...n)){seen.add(k);parents.set(k,[a,b]);queue.push(n);}}}assert.ok(found,'Sin ruta en el mundo de prueba');const path=[end];while(key(...path.at(-1))!==key(...start))path.push(parents.get(key(...path.at(-1))));path.reverse();for(let i=1;i<path.length;i++)if(i===path.length-1||path[i+1][0]-path[i][0]!==path[i][0]-path[i-1][0]||path[i+1][1]-path[i][1]!==path[i][1]-path[i-1][1])await walk(...path[i]);};
 const node=floor.resources.find(n=>n.typeId==='copper-vein'),before=me().crafting.materials.copper||0;await route(node.x+2,node.z);await send({type:'gather',nodeId:node.id});await wait(()=>me().crafting.materials.copper>before,'No recolecta cobre');
 await page.getByRole('button',{name:'Bolsa del personaje',exact:true}).click();let copper=page.locator('.resource-bag [data-material-id="copper"]');await copper.waitFor();assert.equal(await copper.getByRole('button',{name:'Vender Cobre',exact:true}).isEnabled(),false);await page.screenshot({path:out+'41-bolsa-recoleccion.png'});await page.getByRole('button',{name:'Cerrar panel',exact:true}).click();done('Minería real, recursos visibles en la bolsa y venta desactivada lejos del mercader');
 const merchant=floor.npcs.find(n=>n.role==='merchant');await route(merchant.x,merchant.z);await page.getByRole('button',{name:'Tienda',exact:true}).click();copper=page.locator('.resource-bag [data-material-id="copper"]');const owned=me().crafting.materials.copper,col=me().col;
 await copper.getByLabel('Cantidad a vender de Cobre',{exact:true}).fill('1');await copper.getByRole('button',{name:'Vender Cobre',exact:true}).click();await wait(()=>me().crafting.materials.copper===owned-1,'No vende parcialmente');assert.equal(me().col,col+2);
 await copper.getByLabel('Cantidad a vender de Cobre',{exact:true}).fill(String(owned+1));assert.equal(await copper.getByRole('button',{name:'Vender Cobre',exact:true}).isEnabled(),false);await copper.getByRole('button',{name:'Seleccionar todo Cobre',exact:true}).click();await copper.getByRole('button',{name:'Vender Cobre',exact:true}).click();await wait(()=>me().crafting.materials.copper===0,'No vende el resto');assert.equal(me().col,col+owned*2);assert.equal(await copper.count(),0);done('Venta parcial y completa con precio root, rechazo de exceso y conservación exacta de bolsa/monedas');
 const products=world.crafting.shopProducts,visible=await page.locator('.market-product-list article').evaluateAll(rows=>rows.map(r=>r.getAttribute('data-product-id')));
 const weapon=products.find(p=>visible.includes(p.id)&&p.kind==='weapon'&&p.slot==='mainHand'),armor=products.find(p=>visible.includes(p.id)&&p.kind==='armor');assert.ok(weapon&&armor);
 const wallet=me().col,xp=JSON.stringify(me().crafting.professionXp);await page.locator(`[data-product-id="${weapon.id}"]`).getByRole('button',{name:/^Comprar /}).click();await wait(()=>me().crafting.items.length===1,'No compra arma');await page.locator(`[data-product-id="${armor.id}"]`).getByRole('button',{name:/^Comprar /}).click();await wait(()=>me().crafting.items.length===2,'No compra armadura');assert.equal(me().col,wallet-4);assert.equal(JSON.stringify(me().crafting.professionXp),xp);await page.screenshot({path:out+'42-mercado-equipo.png'});done('El mercado vende arma y armadura compatibles, cobra el precio del servidor y entrega dos piezas individuales sin EXP de oficio gratis');
 await page.getByRole('button',{name:'Cerrar panel',exact:true}).click();await route(floor.spawn.x,floor.spawn.z);await page.getByRole('button',{name:'Bolsa del personaje',exact:true}).click();const weaponItem=me().crafting.items.find(i=>i.weapon),armorItem=me().crafting.items.find(i=>i.armor);await page.locator('.crafted-item').filter({hasText:weaponItem.name}).getByRole('button',{name:'Principal',exact:true}).click();await wait(()=>me().crafting.equipped.mainHand===weaponItem.id,'No equipa el arma comprada');await page.locator('.crafted-item').filter({hasText:armorItem.name}).getByRole('button',{name:'Vestir',exact:true}).click();await wait(()=>me().crafting.equipped.armor===armorItem.id,'No viste la armadura comprada');const finalCol=me().col;await page.getByRole('button',{name:'Salir del mundo',exact:true}).click();done('Las piezas compradas se equipan desde la bolsa en el refugio y conservan su identidad');
 await page.goto(url+'/admin');await page.getByLabel('Producto del mercado',{exact:true}).selectOption({index:products.findIndex(p=>p.id===weapon.id)});await page.getByLabel('Precio del producto',{exact:true}).fill('5');await page.getByLabel('Venta de Cobre',{exact:true}).fill('1');await page.getByRole('button',{name:'Guardar y validar',exact:true}).click();await page.getByRole('button',{name:'Aplicar y reconectar →',exact:true}).click();await page.locator('.market-config').scrollIntoViewIfNeeded();await page.screenshot({path:out+'43-mercado-root.png'});const saved=await admin('world');assert.equal(saved.crafting.shopProducts.find(p=>p.id===weapon.id).price,5);assert.equal(saved.crafting.materials.find(m=>m.id==='copper').sellPrice,1);done('Root cambia precios de equipo y de recursos desde los formularios, guarda y aplica el catálogo');
 state=null;await page.goto(url);await page.getByRole('button',{name:/Continuar aventura/}).click();await wait(()=>me()?.id===id&&me()?.crafting?.items.length===2,'No conserva la bolsa al volver');assert.equal(me().col,finalCol);assert.equal(me().crafting.materials.copper,0);assert.equal(me().crafting.equipped.mainHand,weaponItem.id);assert.equal(me().crafting.equipped.armor,armorItem.id);done('Después de aplicar el mundo y volver a entrar se conservan monedas, recursos vendidos y equipo comprado');
 assert.deepEqual(errors,[]);await writeFile(new URL('../../docs/market-browser-result.json',import.meta.url),JSON.stringify({date:new Date().toISOString(),browser:browser.version(),isolatedPriceFixture:true,checks,errors},null,2)+'\n');
}catch(error){await page.screenshot({path:out+'failure-market.png'}).catch(()=>{});console.error({error:error.message,errors,position:me()&&{x:me().x,z:me().z}});throw error;}finally{await browser.close();}
