// Deterministic captures of the exact runtime factories. Uses public seeded props
// from an isolated server; the visual fixture does not claim to simulate gameplay.
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import http from 'node:http';
import path from 'node:path';
const root=new URL('../../',import.meta.url).pathname,out=root+'docs/screenshots';await mkdir(out,{recursive:true});
const world=await(await fetch((process.env.AINCRAD_URL||'http://127.0.0.1:8080')+'/api/world')).json();
const html=`<!doctype html><meta charset="utf-8"><link rel="icon" href="data:,"><style>html,body{margin:0;background:radial-gradient(ellipse at 30% 10%,#dae0d1,#819590);font-family:system-ui;color:#263f3b}canvas{width:100vw;height:100vh;display:block}header{position:absolute;top:24px;left:28px;pointer-events:none}small{font-size:10px;letter-spacing:.2em}h1{font:28px Georgia;margin:7px 0;text-shadow:0 1px 10px #ffffff}p{font-size:12px}</style><header><small>AINCRAD · MUNDO 3D</small><h1 id="title"></h1><p id="subtitle"></p></header><canvas id="c" tabindex="0"></canvas><script type="importmap">{"imports":{"three":"/client/node_modules/three/build/three.module.js","three/addons/":"/client/node_modules/three/examples/jsm/"}}</script><script type="module">
import * as THREE from 'three';window.THREE=THREE;import {WorldRenderer,MonsterPreview} from '/client/src/app/world-renderer.js';import {createCreature,animateCreature} from '/client/src/app/creature-model.js';import {createBuilding,createTree,createResource,createPortal} from '/client/src/app/environment-model.js';import {createSpell,animateEffect} from '/client/src/app/combat-effects.js';import {avatarEnvironment} from '/client/src/app/avatar-model.js';
window.world=await(await fetch('/world.json')).json();window.errors=[];window.mode=new URLSearchParams(location.search).get('mode')||'world';
window.title=(t,s='')=>{document.querySelector('h1').textContent=t;document.querySelector('p').textContent=s;};
if(mode==='world'){
 const spec=world.characterOptions.races[0];window.me={id:'visual-player',kind:'player',name:'Aventurera',appearance:{race:'human',gender:'female',classId:'warrior',specializationId:'swordsman',hairColor:'#765138',skinColor:spec.skinColors[0]},level:5,x:0,z:16,heading:Math.PI,pvp:{status:'Ciudadano'}};window.state={floor:1,you:me.id,players:[me],monsters:[],resources:[],summons:[]};window.sent=[];window.game={world:()=>world,state:()=>state,me:()=>me,connection:()=> 'online',send:e=>sent.push(e),id:me.id};window.view=new WorldRenderer(document.querySelector('canvas'),game,e=>errors.push(e));view.renderer.setAnimationLoop(null);
 window.draw=(floor=1,x=0,z=16,yaw=.24,zoom=18)=>{state.floor=floor;me.x=x;me.z=z;const f=world.floors.find(f=>f.id===floor);state.monsters=[...f.monsters.map(m=>({...m,model:m.kind})),...(f.training?.dummies||[]).map(m=>({...m,kind:'dummy',model:'dummy',training:true})),...f.monsterZones.flatMap(zone=>Array.from({length:Math.min(zone.population,4)},(_,i)=>({...world.monsterSpecies.find(s=>s.id===zone.speciesId),id:zone.id+i,kind:'monster',x:zone.x+Math.sin(i*2.4)*3,z:zone.z+Math.cos(i*2.4)*3,level:zone.minLevel,heading:i*.7})))];view.yaw=yaw;view.zoom=zoom;view.look.set(x,1.1,z);view.lastFrame=0;view.frame();view.look.set(x,1.1,z);view.lastFrame=0;view.frame();};
}else{
 window.helper=Object.create(WorldRenderer.prototype);window.scene=new THREE.Scene();window.renderer=new THREE.WebGLRenderer({canvas:document.querySelector('canvas'),alpha:true,antialias:true});renderer.setSize(innerWidth,innerHeight,false);renderer.setPixelRatio(1);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;window.env=avatarEnvironment(renderer);scene.environment=env.texture;scene.environmentIntensity=.4;scene.add(new THREE.HemisphereLight(0xd9e8ed,0x6a7059,1.0));const light=new THREE.DirectionalLight(0xffe2b5,2.6);light.position.set(-4,7,5);scene.add(light);window.camera=new THREE.PerspectiveCamera(35,innerWidth/innerHeight,.05,300);window.model=null;
 window.asset=(type,id)=>{if(model){scene.remove(model);helper.disposeObject(model);}if(type==='creature')model=createCreature(world.monsterSpecies.find(s=>s.id===id)||{model:id});if(type==='building')model=createBuilding(id);if(type==='resource')model=createResource(world.gathering.resources.find(r=>r.id===id)).mesh;if(type==='portal')model=createPortal();if(type==='tree')model=createTree({leaves:120});if(type==='effects'){model=new THREE.Group();['fire','ice','water','earth','light','shadow'].forEach((el,i)=>{const fx=createSpell(el,1.4);fx.position.set((i%3-1)*3.8,0,(Math.floor(i/3)-.5)*3.6);model.add(fx);animateEffect({mesh:fx,kind:'spell',start:0,duration:1},.35);});}scene.add(model);model.rotation.y=type==='effects'?0:-.3;if(type==='creature')animateCreature(model,.85,false,0);const bounds=new THREE.Box3().setFromObject(model),s=bounds.getBoundingSphere(new THREE.Sphere()),fov=THREE.MathUtils.degToRad(35),d=s.radius/Math.sin(Math.min(fov,2*Math.atan(Math.tan(fov/2)*camera.aspect))/2)*1.03;camera.position.copy(s.center).add(new THREE.Vector3(d*.12,d*(type==='effects'?.80:type==='creature'?.15:.36),d));camera.lookAt(s.center);renderer.render(scene,camera);};
}
window.metrics=()=>{const r=window.renderer||view.renderer;return{triangles:r.info.render.triangles,drawCalls:r.info.render.calls,memory:{...r.info.memory},error:r.getContext().getError()}};window.ready=true;</script>`;
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname==='/inspect'){res.setHeader('Content-Type','text/html');return res.end(html);}if(u.pathname==='/world.json'){res.setHeader('Content-Type','application/json');return res.end(JSON.stringify(world));}const f=path.resolve(root,'.'+decodeURIComponent(u.pathname));if(!['client/src/','client/node_modules/three/'].some(p=>f.startsWith(root+p)))throw Error();res.setHeader('Content-Type','text/javascript');res.end(await readFile(f));}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']});
const errors=[],checks=[],metrics=[];
try{const page=await browser.newPage({viewport:{width:1200,height:850}});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.goto(`http://127.0.0.1:${server.address().port}/inspect`);await page.waitForFunction(()=>window.ready&&document.hasFocus());
 for(const [id,f,x,z,yaw,zoom,t]of [['20-refugio-detallado',1,0,16,.3,19,'El refugio de los comienzos'],['21-talleres',1,0,22,1.0,16,'Oficios · piedra, madera y tejido'],['22-bosque-cristal',2,world.floors[1].spawn.x,world.floors[1].spawn.z,-.22,22,'El bosque de cristal'],['23-portal',1,world.floors[0].portal.x,world.floors[0].portal.z+3,.42,12,'La puerta al siguiente piso']]){await page.evaluate(({f,x,z,yaw,zoom,t})=>{title(t,'Escena real del renderizador · vista de inspección');draw(f,x,z,yaw,zoom);},{f,x,z,yaw,zoom,t});const data=await page.evaluate(()=>metrics());assert.equal(data.error,0);assert.ok(data.drawCalls>0);metrics.push({id,...data});await page.screenshot({path:out+'/'+id+'.png'});console.log(id,data.drawCalls,data.triangles);}
 checks.push('Ambos pisos y los talleres/portal se dibujan con los props públicos del servidor, sin errores WebGL');
 const picks=await page.evaluate(()=>{const clickAt=(x,y,z)=>{view.camera.updateMatrixWorld();const p=new THREE.Vector3(x,y,z).project(view.camera),rect=view.canvas.getBoundingClientRect();view.click({clientX:rect.left+(p.x+1)*rect.width/2,clientY:rect.top+(1-p.y)*rect.height/2});return sent.at(-1);};draw(1,0,27,0,14);const dummy=clickAt(-2,1.3,27);draw(1,-14,6,0,12);const ore=clickAt(-16,.5,6);return {dummy,ore};});assert.equal(picks.dummy.type,'target');assert.equal(picks.dummy.id,'dummy-straw');assert.equal(picks.ore.type,'gather');assert.equal(picks.ore.nodeId,'resource-1-0');checks.push('El picking sobre las mallas nuevas selecciona el muñeco y la veta de cobre correctos');

 const lifecycle=await page.evaluate(()=>{draw(1);view.setQuality('low');draw(1);const low=metrics();view.setQuality('high');draw(1);const high=metrics();view.setQuality('balanced');draw(1);const start=metrics();for(let i=0;i<3;i++){draw(2);draw(1);}return {low,high,start,end:metrics()};});assert.ok(lifecycle.high.triangles>lifecycle.low.triangles);assert.equal(lifecycle.start.memory.geometries,lifecycle.end.memory.geometries);assert.equal(lifecycle.start.memory.textures,lifecycle.end.memory.textures);checks.push('Tres calidades y seis cambios de piso liberan las geometrías y texturas anteriores');
 await page.evaluate(()=>view.dispose());await page.goto(`http://127.0.0.1:${server.address().port}/inspect?mode=assets`);await page.waitForFunction(()=>window.ready);for(const s of world.monsterSpecies){await page.evaluate(s=>{title(s.name,'Modelo usado por las criaturas y el editor root');asset('creature',s.id);},s);const data=await page.evaluate(()=>metrics());assert.equal(data.error,0);metrics.push({id:s.id,...data});await page.screenshot({path:out+'/creature-'+s.id+'.png'});console.log('criatura',s.id);}
 checks.push('Siete especies detalladas, con materiales y geometría idénticos a los del juego y root');
 for(const [type,id,label]of [['building','smithy','Herrería'],['building','tailor','Sastrería'],['building','shop','Tienda'],['resource','pine-tree','Pino maderable'],['resource','oak-tree','Roble maderable'],['resource','crystal-vein','Cristal arcano'],['effects','elements','Magia elemental']]){await page.evaluate(({type,id,label})=>{title(label,'Modelo 3D procedural · materiales propios');asset(type,id);},{type,id,label});assert.equal((await page.evaluate(()=>metrics())).error,0);await page.screenshot({path:out+'/detail-'+id+'.png'});console.log('detalle',id);}
 checks.push('Talleres, tres recursos y efectos de seis elementos inspeccionados con las mismas fábricas de mallas');assert.deepEqual(errors,[]);await writeFile(root+'docs/world-visual-result.json',JSON.stringify({date:new Date().toISOString(),browser:browser.version(),checks,metrics,picks,lifecycle,errors},null,2)+'\n');
}catch(e){console.error(e,errors);throw e;}finally{await browser.close();server.close();}
