import {registerAndLogin} from './player-account.mjs';
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
const url=process.env.AINCRAD_URL||'http://127.0.0.1:8080',password=process.env.AINCRAD_ADMIN_PASSWORD;if(!password)throw Error('Usa un servidor aislado y AINCRAD_ADMIN_PASSWORD.');
const out=new URL('../../docs/screenshots/',import.meta.url).pathname;
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']});
const ctx=await browser.newContext({viewport:{width:1365,height:960}}),page=await ctx.newPage();page.setDefaultTimeout(60000);const errors=[],checks=[],events=[];let state;
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().startsWith('WebSocket connection'))errors.push(m.text())});page.on('websocket',ws=>ws.on('framereceived',({payload})=>{try{const e=JSON.parse(String(payload));if(e.type==='state')state=e;else events.push(e);}catch{}}));
await page.addInitScript(()=>{const Original=window.WebSocket;window.WebSocket=class extends Original{constructor(...args){super(...args);window.__testSocket=this;}};});
const me=()=>state?.players.find(p=>p.id===state.you),send=e=>page.evaluate(e=>window.__testSocket.send(JSON.stringify(e)),e);
const wait=async(fn,msg,ms=45000)=>{const end=Date.now()+ms;while(Date.now()<end){if(fn())return;await new Promise(r=>setTimeout(r,100));}throw Error(msg);};
const done=s=>{checks.push(s);console.log(s);};
try{
 await registerAndLogin(ctx.request,url);
 await page.goto(url);await page.getByRole('button',{name:'Chica',exact:true}).click();await page.getByLabel('Raza',{exact:true}).selectOption('elf');await page.getByLabel('Clase',{exact:true}).selectOption('healer');await page.getByLabel('TU NOMBRE DE AVENTURERO').fill('Aria');await page.getByRole('button',{name:/Entrar al mundo/}).click();await wait(()=>me(),'Entrada fallida');await page.waitForTimeout(1000);await page.locator('#world-canvas').focus();const initial=me().z;await page.keyboard.down('KeyW');await page.waitForTimeout(450);await page.keyboard.up('KeyW');await wait(()=>me().z<initial-.6,'W no mueve al personaje');await page.keyboard.press('KeyE');await page.locator('.dialogue').waitFor();assert.match(await page.locator('.dialogue').innerText(),/Lyra/);await page.getByRole('button',{name:'Continuar →',exact:true}).click();await page.screenshot({path:out+'24-juego-renovado.png'});done('Angular, la elfa, los NPC, los talleres, movimiento WASD y conversación con Lyra funcionan juntos');
 await page.getByRole('button',{name:'Ajustes gráficos',exact:true}).click();for(const value of ['low','high','balanced']){await page.getByLabel('Calidad del mundo',{exact:true}).selectOption(value);await page.waitForFunction(v=>localStorage.getItem('aincrad-graphics-v1')===v,value);await page.waitForTimeout(600);assert.equal(me().name,'Aria');}await page.screenshot({path:out+'25-calidad-grafica.png'});await page.getByRole('button',{name:'Cerrar panel',exact:true}).click();done('Las tres calidades se aplican y persisten sin desconectar ni sustituir el personaje');
 await send({type:'move',x:0,z:27});await wait(()=>Math.hypot(me().x,me().z-27)<.4,'No llega al patio');const dummy=state.monsters.find(m=>m.id==='dummy-straw');assert.ok(dummy);await send({type:'target',id:dummy.id,kind:'monster'});await wait(()=>me().target===dummy.id,'No selecciona muñeco');await page.getByRole('button',{name:/ESPACIO.*Ataque/}).click();await wait(()=>events.some(e=>e.type==='hit'&&e.target===dummy.id),'No hubo golpe del servidor');const ally=state.monsters.find(m=>m.id==='dummy-ally');await send({type:'target',id:ally.id,kind:'monster'});await send({type:'attack',skill:true});await wait(()=>events.some(e=>e.type==='heal'&&e.source===me().id),'No hubo curación del servidor');await page.screenshot({path:out+'26-practica-renovada.png'});done('Selección, daño y curación de muñecos se validan en el servidor con los nuevos modelos y efectos');
 // One page at a time: software WebGL is not a hardware throughput benchmark.
 await page.goto(url+'/admin');await page.getByLabel('Contraseña',{exact:true}).fill(password);await page.getByRole('button',{name:/Entrar como root/}).click();await page.getByRole('heading',{name:'Construye el siguiente nivel.'}).waitFor();
 const species=page.locator('.species-config');await species.getByLabel('Especie a editar',{exact:true}).selectOption({label:'Centinela'});await species.getByLabel('Color de especie',{exact:true}).fill('#557c99');await species.locator('canvas').scrollIntoViewIfNeeded();await page.waitForTimeout(500);await species.locator('canvas').screenshot({path:out+'27-centinela-root.png'});
 await page.getByLabel('Requiere derrotar a un Centinela',{exact:true}).uncheck();await page.getByLabel('Portal Z',{exact:true}).fill('12');const save=page.waitForResponse(r=>r.url().endsWith('/api/admin/world')&&r.request().method()==='PUT');await page.getByRole('button',{name:'Guardar y validar',exact:true}).click();assert.ok((await save).ok());const apply=page.waitForResponse(r=>r.url().endsWith('/api/admin/reload'));await page.getByRole('button',{name:'Aplicar y reconectar →',exact:true}).click();assert.ok((await apply).ok());const updated=await(await ctx.request.get(url+'/api/world')).json();assert.equal(updated.monsterSpecies.find(s=>s.model==='guardian').color,'#557c99');assert.equal(updated.floors[0].portal.z,12);done('Root previsualiza el Centinela nuevo, cambia su color y aplica el mundo; portal de prueba acercado al refugio');
 state=null;await page.goto(url);await page.getByRole('button',{name:/Continuar aventura/}).click();await wait(()=>me(),'No recupera personaje');assert.equal(await page.evaluate(()=>localStorage.getItem('aincrad-graphics-v1')),'balanced');await send({type:'move',x:0,z:12});await wait(()=>Math.hypot(me().x,me().z-12)<.5,'No llega al portal de prueba');await send({type:'portal'});await wait(()=>state.floor===2,'No atraviesa portal');await page.waitForTimeout(700);await page.screenshot({path:out+'28-juego-cristal.png'});assert.equal(me().appearance.race,'elf');done('El portal carga el bosque de cristal y conserva identidad, progreso y ajuste gráfico');
 assert.deepEqual(errors,[]);await writeFile(new URL('../../docs/world-browser-result.json',import.meta.url),JSON.stringify({date:new Date().toISOString(),browser:browser.version(),checks,events:events.filter(e=>['hit','heal'].includes(e.type)).map(e=>({type:e.type,target:e.target,damage:e.damage,amount:e.amount})),errors},null,2)+'\n');
}catch(e){await page.screenshot({path:out+'failure-world.png'}).catch(()=>{});console.error({error:e.message,errors,state:me()&&{x:me().x,z:me().z,floor:state.floor,target:me().target},events:events.slice(-5)});throw e;}finally{await browser.close();}
