package dev.aincrad;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import static org.junit.jupiter.api.Assertions.*;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.atomic.AtomicLong;

class BestiaryZonesTest {
 @TempDir Path dir;ObjectMapper json=new ObjectMapper();PlayerStore store;GameWorld world;AtomicLong now=new AtomicLong(2_000_000_000_000L);
 @BeforeEach void setup()throws Exception{store=new PlayerStore(dir.resolve("players"),json);world=new GameWorld(WorldData.load(Path.of("../world/world.json"),json),store,(id,e)->{},now::get);}
 @AfterEach void close()throws Exception{store.close();}
 GameWorld.Player player()throws Exception{var n=world.join("Cazador","",new WorldData.Appearance("male","calm","#342f32","#dfb18b","mage","human","fire"));return world.online.get(n.get("id"));}
 GameWorld.Monster mob(String id){return world.monsters.values().stream().filter(m->m.kind.equals(id)&&m.zone!=null).findFirst().orElseThrow();}
 void cmd(GameWorld.Player p,String type,Object... fields){var n=json.createObjectNode().put("type",type);for(int i=0;i<fields.length;i+=2)n.set((String)fields[i],json.valueToTree(fields[i+1]));world.command(p.id,n);}
 void near(GameWorld.Player p,GameWorld.Monster m){p.floor=m.floor;p.x=m.x+.4;p.z=m.z;p.target=m.id;p.targetKind="monster";}
 void isolate(GameWorld.Monster m){for(var other:world.monsters.values())if(other!=m&&!other.practice()){other.hp=0;other.respawnAt=Double.MAX_VALUE;}}
 void tick(int n){for(int i=0;i<n;i++){now.addAndGet(50);world.tick(.05);}}
 @Test void fiveZonesGenerateStableWalkablePopulationsWithAllLevelRanges()throws Exception{var first=world.data.floors.stream().flatMap(f->f.zoneSpawns.stream()).toList();assertEquals(26,first.size());assertEquals(Set.of("slime","dog","goblin","orc","troll"),new HashSet<>(first.stream().map(Bestiary.Placed::speciesId).toList()));for(var f:world.data.floors)for(var m:f.zoneSpawns){assertTrue(world.data.walkable(f.id,m.x(),m.z()));assertTrue(Bestiary.inside(m.zone(),m.x(),m.z()));assertTrue(m.level()>=m.zone().minLevel()&&m.level()<=m.zone().maxLevel());}world.data.validateAndGenerate();assertEquals(first,world.data.floors.stream().flatMap(f->f.zoneSpawns.stream()).toList());assertEquals(38,world.monsters.size());assertEquals(48,world.monsters.get("boar-1").maxHp);assertEquals(240,world.monsters.get("guardian-1").maxHp);}
 @Test void speciesScaleLifeDamageDefenseAndRewardsByLevel(){for(String id:List.of("slime","dog","goblin","orc","troll")){var m=mob(id);assertEquals(m.species.hp(m.level),m.maxHp);assertTrue(m.species.hp(20)>m.species.hp(1));assertTrue(m.species.damage(20)>m.species.damage(1));assertTrue(m.species.xp(20)>m.species.xp(1));assertEquals(m.level,m.view().get("level"));assertEquals(m.zone.id(),m.view().get("zoneId"));}assertEquals(700,mob("troll").maxHp);}
 @Test void armorMitigatesDamageAndClientCannotForgeCreatureLevelOrRewards()throws Exception{var p=player();var m=mob("orc");near(p,m);int hp=m.hp;cmd(p,"attack","level",999,"damage",99999,"xp",100000);assertEquals(hp-Math.max(1,p.damage()-m.species.defense(m.level)),m.hp);assertEquals(11,m.level);assertEquals(0,p.xp);assertEquals(0,p.col);}
 @Test void leveledKillPaysOnceAndDoesNotCountAsBoarOrUnlockBossPortal()throws Exception{var p=player();p.quest=true;var m=mob("orc");near(p,m);m.hp=1;int iron=p.crafting.materials.get("iron"),leather=p.crafting.materials.get("leather");cmd(p,"attack");assertEquals(0,m.hp);assertEquals(m.species.xp(m.level),p.xp);assertEquals(m.species.col(m.level),p.col);assertEquals(iron+3,p.crafting.materials.get("iron"));assertEquals(leather+2,p.crafting.materials.get("leather"));assertEquals(0,p.kills);assertFalse(p.unlocked);cmd(p,"attack");assertEquals(m.species.xp(m.level),p.xp);}
 @Test void zoneRespawnPreservesIdentityLevelAndHomeWithoutDuplicatingRewards()throws Exception{var p=player();var m=mob("slime");near(p,m);m.hp=1;cmd(p,"attack");int xp=p.xp,level=m.level;String id=m.id;p.floor=2;p.x=0;p.z=15;tick(300);assertEquals(0,m.hp);tick(25);assertSame(m,world.monsters.get(id));assertEquals(level,m.level);assertEquals(m.maxHp,m.hp);assertEquals(m.homeX,m.x,.001);assertEquals(m.homeZ,m.z,.001);assertEquals(xp,p.xp);}
 @Test void leavingZoneClearsThreatAndReturningCreaturesCannotBeFarmed()throws Exception{var p=player();var m=mob("dog");isolate(m);m.x=(m.homeX+m.zone.x())/2;m.z=(m.homeZ+m.zone.z())/2;m.hp--;m.participants.add(p.id);p.floor=m.floor;p.x=0;p.z=16;tick(1);assertTrue(m.returning);assertTrue(m.participants.isEmpty());int hp=m.hp;near(p,m);cmd(p,"attack");assertEquals(hp,m.hp);p.x=0;p.z=16;tick(170);assertFalse(m.returning);assertEquals(m.maxHp,m.hp);assertEquals(0,p.xp);assertTrue(Bestiary.inside(m.zone,m.x,m.z));}
 @Test void blockedReturnRecoversAtHomeAfterEightSeconds()throws Exception{var m=mob("goblin");m.returning=true;m.evadeAt=0;m.x=m.zone.x();m.z=m.zone.z();m.hp=1;var f=world.data.floor(m.floor);f.props.add(new WorldData.Prop("tree",m.x,m.z,1,0,3));tick(165);assertFalse(m.returning);assertEquals(m.maxHp,m.hp);assertEquals(m.homeX,m.x,.001);assertEquals(m.homeZ,m.z,.001);}
 @Test void creatureAttackUsesItsScaledDamage()throws Exception{var p=player();var m=mob("orc");isolate(m);near(p,m);int hp=p.hp;tick(1);assertEquals(hp-Math.max(1,m.species.damage(m.level)-p.defense()),p.hp);}
 @Test void trollTelegraphsBeforeApplyingItsHeavyHit()throws Exception{var p=player();var m=mob("troll");isolate(m);near(p,m);int hp=p.hp;tick(1);assertTrue(m.windupUntil>0);assertEquals(hp,p.hp);tick(20);assertEquals(hp-Math.max(1,m.species.damage(m.level)-p.defense()),p.hp);}
 @Test void unsafeOverlappingAndUnknownZonesAreRejected(){var f=world.data.floors.get(0);var base=f.monsterZones.get(0);f.monsterZones.add(new Bestiary.Zone("bad","Invasión","slime",1,3,0,16,4,3,20));assertThrows(IllegalArgumentException.class,()->world.data.validateAndGenerate());f.monsterZones.remove(f.monsterZones.size()-1);f.monsterZones.add(new Bestiary.Zone("bad","Solapada","slime",1,3,base.x(),base.z(),4,3,20));assertThrows(IllegalArgumentException.class,()->world.data.validateAndGenerate());f.monsterZones.remove(f.monsterZones.size()-1);f.monsterZones.add(new Bestiary.Zone("bad","Desconocida","missing",1,3,0,0,4,3,20));assertThrows(IllegalArgumentException.class,()->world.data.validateAndGenerate());}
 @Test void populationCannotExceedWalkableCapacityOrUseDuplicateIds(){var f=world.data.floors.get(0);f.monsterZones.add(new Bestiary.Zone("dense","Demasiado densa","slime",1,3,35,0,3,30,20));assertThrows(IllegalArgumentException.class,()->world.data.validateAndGenerate());f.monsterZones.remove(f.monsterZones.size()-1);f.monsters.add(new WorldData.Spawn("slime-marsh-1","boar","Duplicado",0,0,1));assertThrows(IllegalArgumentException.class,()->world.data.validateAndGenerate());}
 @Test void rootCanCreateSpeciesVariantsAndManualLevelSpawns()throws Exception{ObjectNode tree=json.valueToTree(world.data);var species=(ObjectNode)tree.withArray("monsterSpecies").get(2).deepCopy();species.put("id","azure-slime").put("name","Slime azul").put("color","#55aadd").put("baseHp",100);tree.withArray("monsterSpecies").add(species);((ObjectNode)tree.withArray("floors").get(0)).withArray("monsters").addObject().put("id","blue-1").put("kind","azure-slime").put("name","Slime azul").put("x",0).put("z",0).put("level",5);var updated=json.treeToValue(tree,WorldData.class);updated.validateAndGenerate();var next=new GameWorld(updated,store,(id,e)->{},now::get);assertEquals(148,next.monsters.get("blue-1").hp);assertEquals("slime",next.monsters.get("blue-1").view().get("model"));}
 @Test void revisionSixMigratesWithoutMovingOrReplacingExistingWorld()throws Exception{var file=dir.resolve("world-v6.json");try(var in=getClass().getResourceAsStream("/world-v6.json")){Files.copy(in,file);}var before=json.readTree(file.toFile());var migrated=WorldData.load(file,json);assertEquals(7,migrated.schemaRevision);assertEquals(7,migrated.monsterSpecies.size());assertEquals(4,migrated.floors.get(0).training.dummies.size());assertTrue(migrated.floors.stream().allMatch(f->f.monsterZones.isEmpty()));for(var f:migrated.floors)for(var m:f.monsters)assertEquals(1,m.level());assertEquals(before.path("floors").get(0).path("spawn").path("x").asDouble(),migrated.floors.get(0).spawn.x());assertEquals(before.path("floors").get(0).path("spawn").path("z").asDouble(),migrated.floors.get(0).spawn.z());assertEquals(before.path("crafting").path("monsterDrops").path("boar"),json.valueToTree(migrated.crafting.monsterDrops.get("boar")));}
 @Test void damagedCreaturePursuesItsRangedAttackerBeyondDetectionInsideItsTerritory()throws Exception{var p=player();var m=mob("slime");isolate(m);m.x=m.homeX=m.zone.x()-3;m.z=m.homeZ=m.zone.z();p.floor=m.floor;p.x=m.zone.x()+3;p.z=m.z;p.target=m.id;cmd(p,"attack");int hp=m.hp;assertTrue(hp<m.maxHp);tick(1);assertFalse(m.returning);assertEquals(hp,m.hp);assertTrue(m.x>m.homeX);}

}
