package dev.aincrad;

import com.fasterxml.jackson.databind.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import static org.junit.jupiter.api.Assertions.*;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.atomic.AtomicLong;

class CraftingGatheringTest {
 @TempDir Path dir;ObjectMapper json=new ObjectMapper();PlayerStore store;GameWorld world;AtomicLong now=new AtomicLong(2_000_000_000_000L);
 @BeforeEach void setup()throws Exception{store=new PlayerStore(dir.resolve("players"),json);world=new GameWorld(WorldData.load(Path.of("../world/world.json"),json),store,(id,e)->{},now::get);}
 @AfterEach void close()throws Exception{store.close();}
 GameWorld.Player player(String cls)throws Exception{var w=world.join("Artesano","",new WorldData.Appearance("female","calm","#342f32","#dfb18b",cls,"human"));var p=world.online.get(w.get("id"));p.col=1000;return p;}
 void cmd(GameWorld.Player p,String type,Object... fields){var n=json.createObjectNode().put("type",type);for(int i=0;i<fields.length;i+=2)n.set((String)fields[i],json.valueToTree(fields[i+1]));world.command(p.id,n);}
 void station(GameWorld.Player p,String role){var n=world.data.floor(1).npcs.stream().filter(a->a.role().equals(role)).findFirst().orElseThrow();p.floor=1;p.x=n.x();p.z=n.z();}
 Crafting.Recipe recipe(String cls,String slot,int level){return world.data.crafting.recipes.stream().filter(r->r.slot().equals(slot)&&(!cls.equals("warrior")||!r.targetId().contains("-guardia-")&&!r.targetId().contains("-assassin")&&!r.targetId().contains("-tank"))&&r.minProfessionLevel()==level&&(r.kind().equals("weapon")?world.data.characterOptions.weaponSets.stream().anyMatch(s->s.id().equals(r.targetId())&&s.classId().equals(cls)):world.data.characterOptions.equipmentSets.stream().anyMatch(s->s.id().equals(r.targetId())&&s.classId().equals(cls)&&s.gender().equals("female")))).findFirst().orElseThrow();}
 Crafting.Item make(GameWorld.Player p,Crafting.Recipe r){station(p,world.data.crafting.professions.stream().filter(j->j.id().equals(r.professionId())).findFirst().orElseThrow().stationRole());cmd(p,"craft","recipeId",r.id());return p.crafting.items.values().stream().reduce((a,b)->b).orElseThrow();}
 @Test void forgeCreatesAnOwnedWeaponAndUpgradesWithRealStats()throws Exception{var p=player("warrior");var r=recipe("warrior","mainHand",1);int oldDamage=p.damage();var item=make(p,r);assertEquals(990,p.col);assertEquals(3,p.crafting.materials.get("iron"));assertEquals(25,p.crafting.professionXp.get("blacksmith"));cmd(p,"craftEquip","itemId",item.id,"slot","mainHand");assertEquals(oldDamage+1,p.damage());p.hp=40;cmd(p,"craftUpgrade","itemId",item.id);assertEquals(1,p.crafting.items.get(item.id).upgrade);assertEquals(oldDamage+2,p.damage());assertEquals(40,p.hp);assertEquals(975,p.col);assertEquals(1,p.crafting.materials.get("iron"));assertEquals(35,p.crafting.professionXp.get("blacksmith"));world.leave(p.id);var next=new GameWorld(world.data,store,(id,e)->{},now::get).profiles.get(p.hash);assertEquals(item.id,next.crafting.equipped.get("mainHand"));assertEquals(p.damage(),next.damage());}
 @Test void tailorCreatesWearableClothesForClassGenderAndLevel()throws Exception{var p=player("healer");var r=recipe("healer","armor",1);int hp=p.maxHp();var item=make(p,r);cmd(p,"craftEquip","itemId",item.id,"slot","armor");assertEquals(hp+5,p.maxHp());assertEquals(110,p.hp);assertEquals(25,p.crafting.professionXp.get("tailor"));cmd(p,"craftUpgrade","itemId",item.id);assertEquals(hp+10,p.maxHp());assertTrue(p.modifier("healing")>=1);}
 @Test void noCraftFarAwayInCombatWithoutFundsOrUsingForgedCosts()throws Exception{var p=player("warrior");var r=recipe("warrior","mainHand",1);p.x=0;p.z=-15;assertThrows(IllegalArgumentException.class,()->cmd(p,"craft","recipeId",r.id()));station(p,"smith");p.pvp.combatUntil=now.get()+10000;assertThrows(IllegalArgumentException.class,()->cmd(p,"craft","recipeId",r.id()));p.pvp.combatUntil=0;p.col=0;var before=p.crafting.copy();assertThrows(IllegalArgumentException.class,()->cmd(p,"craft","recipeId",r.id(),"colCost",0,"materials",Map.of(),"experience",9999));assertEquals(before.materials,p.crafting.materials);assertTrue(p.crafting.items.isEmpty());assertEquals(0,p.crafting.professionXp.get("blacksmith"));}
 @Test void objectsCannotBeEquippedByAnotherPlayerOrDuplicatedAcrossSlots()throws Exception{var a=player("warrior");var b=player("warrior");var i=make(a,recipe("warrior","mainHand",1));assertThrows(IllegalArgumentException.class,()->cmd(b,"craftEquip","itemId",i.id,"slot","mainHand"));cmd(a,"craftEquip","itemId",i.id,"slot","mainHand");cmd(a,"craftEquip","itemId",i.id,"slot","offHand");assertFalse(a.crafting.equipped.containsKey("mainHand"));assertEquals(i.id,a.crafting.equipped.get("offHand"));}
 @Test void craftedTwoHandStaffBlocksSecondaryAndTemplateSelectionClearsOverrides()throws Exception{var p=player("mage");var staff=make(p,recipe("mage","mainHand",1));cmd(p,"craftEquip","itemId",staff.id,"slot","mainHand");assertNull(p.weapons().offHand());p.crafting.materials.put("wood",20);p.crafting.materials.put("crystal",20);var wandRecipe=world.data.crafting.recipes.stream().filter(r->r.targetId().equals("mage-canalizador-1")&&r.slot().equals("offHand")).findFirst().orElseThrow();var wand=make(p,wandRecipe);assertThrows(IllegalArgumentException.class,()->cmd(p,"craftEquip","itemId",wand.id,"slot","offHand"));world.equip(p.id,"mage-canalizador-1",false);assertTrue(p.crafting.equipped.isEmpty());cmd(p,"craftEquip","itemId",wand.id,"slot","offHand");assertEquals("wand",p.weapons().offHand().kind());}
 @Test void shopUsesServerPricesAndRejectsNegativeOrFractionalQuantities()throws Exception{var p=player("warrior");station(p,"merchant");int before=p.crafting.materials.get("iron");cmd(p,"shopBuy","materialId","iron","quantity",3,"price",0);assertEquals(982,p.col);assertEquals(before+3,p.crafting.materials.get("iron"));assertThrows(IllegalArgumentException.class,()->cmd(p,"shopBuy","materialId","iron","quantity",-1));assertThrows(IllegalArgumentException.class,()->cmd(p,"shopBuy","materialId","iron","quantity",1.5));cmd(p,"shopBuy","materialId","potion","quantity",2);assertEquals(7,p.potions);assertEquals(958,p.col);}
 @Test void saleIsSingleUseAndRequiresUnequippedOwnedObject()throws Exception{var p=player("warrior");var i=make(p,recipe("warrior","mainHand",1));cmd(p,"craftEquip","itemId",i.id,"slot","mainHand");station(p,"merchant");assertThrows(IllegalArgumentException.class,()->cmd(p,"shopSell","itemId",i.id));p.x=0;p.z=16;cmd(p,"craftUnequip","slot","mainHand");station(p,"merchant");cmd(p,"shopSell","itemId",i.id);assertEquals(993,p.col);assertTrue(p.crafting.items.isEmpty());assertThrows(IllegalArgumentException.class,()->cmd(p,"shopSell","itemId",i.id));}
 @Test void levelAndCapacityAndMaximumUpgradeAreEnforced()throws Exception{var p=player("warrior");station(p,"smith");assertThrows(IllegalArgumentException.class,()->cmd(p,"craft","recipeId",recipe("warrior","mainHand",2).id()));world.data.crafting.maxInventory=1;var i=make(p,recipe("warrior","mainHand",1));assertThrows(IllegalArgumentException.class,()->cmd(p,"craft","recipeId",i.recipeId));p.crafting.items.get(i.id).upgrade=5;assertThrows(IllegalArgumentException.class,()->cmd(p,"craftUpgrade","itemId",i.id));}
 @Test void rootControlsProfessionXpAndMaterialsButPlayerCommandsCannot()throws Exception{var p=player("healer");var update=json.createObjectNode();update.set("professionXp",json.valueToTree(Map.of("tailor",300)));update.set("materials",json.valueToTree(Map.of("fiber",80,"mithril",10)));world.craftingProgress(p.id,update);assertEquals(4,Crafting.level(world.data.crafting,p.crafting,"tailor"));assertEquals(80,p.crafting.materials.get("fiber"));assertThrows(IllegalArgumentException.class,()->cmd(p,"craftingProgress","professionXp",Map.of("tailor",10000)));((com.fasterxml.jackson.databind.node.ObjectNode)update.get("materials")).put("fiber",-10);assertThrows(IllegalArgumentException.class,()->world.craftingProgress(p.id,update));assertEquals(80,p.crafting.materials.get("fiber"));}
 @Test void buildingsAndResourceNodesUseServerCollision()throws Exception{var f=world.data.floor(1);assertEquals(3,f.buildings.size());assertEquals(Set.of("smithy","tailor","shop"),new HashSet<>(f.buildings.stream().map(WorldData.Building::kind).toList()));for(var b:f.buildings)assertFalse(world.data.walkable(1,b.x(),b.z()));for(var n:f.resources)assertFalse(world.data.walkable(1,n.x(),n.z()));assertTrue(f.npcs.stream().anyMatch(n->n.role().equals("tailor")));assertTrue(f.npcs.stream().anyMatch(n->n.role().equals("merchant")));}
 Gathering.Node node(String type){return world.data.floors.stream().flatMap(f->f.resources.stream()).filter(n->n.typeId().equals(type)).findFirst().orElseThrow();}
 void near(GameWorld.Player p,Gathering.Node n){p.floor=world.data.floors.stream().filter(f->f.resources.contains(n)).findFirst().orElseThrow().id;p.x=n.x()-2;p.z=n.z();}
 @Test void miningGrantsMaterialAndXpAndSharesDepletionBetweenPlayers()throws Exception{var a=player("warrior");var b=player("mage");var n=node("iron-vein");near(a,n);near(b,n);cmd(a,"gather","nodeId",n.id(),"amount",99999);assertEquals(9,a.crafting.materials.get("iron"));assertEquals(25,a.crafting.professionXp.get("mining"));assertThrows(IllegalArgumentException.class,()->cmd(b,"gather","nodeId",n.id()));now.addAndGet(26000);cmd(b,"gather","nodeId",n.id());assertEquals(9,b.crafting.materials.get("iron"));}
 @Test void lumberjackHasUnlocksAndReachAndNoCombatGathering()throws Exception{var p=player("healer");var pine=node("pine-tree");assertThrows(IllegalArgumentException.class,()->cmd(p,"gather","nodeId",pine.id()));near(p,pine);cmd(p,"gather","nodeId",pine.id());assertEquals(7,p.crafting.materials.get("wood"));now.addAndGet(2000);var oak=node("oak-tree");near(p,oak);assertThrows(IllegalArgumentException.class,()->cmd(p,"gather","nodeId",oak.id()));p.crafting.professionXp.put("lumberjack",100);cmd(p,"gather","nodeId",oak.id());assertEquals(3,p.crafting.materials.get("oak"));now.addAndGet(40000);p.pvp.combatUntil=now.get()+10000;assertThrows(IllegalArgumentException.class,()->cmd(p,"gather","nodeId",oak.id()));}
 @Test void harvestReceiptRecoversRewardExactlyOnceAndDepletionAcrossRestart()throws Exception{var p=player("warrior");var old=p.profile();var n=node("iron-vein");near(p,n);cmd(p,"gather","nodeId",n.id());store.save(old);var next=new GameWorld(world.data,store,(id,e)->{},now::get);var loaded=next.profiles.get(p.hash);assertEquals(9,loaded.crafting.materials.get("iron"));assertEquals(25,loaded.crafting.professionXp.get("mining"));var again=new GameWorld(world.data,store,(id,e)->{},now::get);assertEquals(9,again.profiles.get(p.hash).crafting.materials.get("iron"));var other=world.join("Recolector","");var b=world.online.get(other.get("id"));near(b,n);assertThrows(IllegalArgumentException.class,()->cmd(b,"gather","nodeId",n.id()));}
 @Test void recipesForHigherTiersConsumeRareMaterialsAndValidationRejectsBadReferences()throws Exception{assertTrue(world.data.crafting.recipes.stream().anyMatch(r->r.materials().containsKey("mithril")));assertTrue(world.data.crafting.recipes.stream().anyMatch(r->r.materials().containsKey("ancientwood")));world.data.crafting.initialMaterials.put("fake",1);assertThrows(IllegalArgumentException.class,world.data::validateAndGenerate);world.data.crafting.initialMaterials.remove("fake");world.data.floor(1).resources.add(new Gathering.Node("bad-node","iron-vein",10,19));assertThrows(IllegalArgumentException.class,world.data::validateAndGenerate);}
 @Test void equipmentRemainsOwnedButUnequipsAfterClassChange()throws Exception{var p=player("warrior");var i=make(p,recipe("warrior","mainHand",1));cmd(p,"craftEquip","itemId",i.id,"slot","mainHand");world.updateCharacter(p.id,p.name,new WorldData.Appearance("female","calm","#342f32","#dfb18b","mage","human"),null,null,null,true);assertTrue(p.crafting.equipped.isEmpty());assertTrue(p.crafting.items.containsKey(i.id));assertEquals("staff",p.weapons().mainHand().kind());}
 @Test void gatheredResourcesCanBeSoldPartiallyAndDoNotReturnAfterRestart()throws Exception{
  var p=player("warrior");var node=node("iron-vein");near(p,node);cmd(p,"gather","nodeId",node.id());assertEquals(9,p.crafting.materials.get("iron"));
  station(p,"merchant");int price=Crafting.materialSalePrice(world.data.crafting,world.data.crafting.materials.stream().filter(m->m.id().equals("iron")).findFirst().orElseThrow()),before=p.col;
  cmd(p,"shopSellMaterial","materialId","iron","quantity",4,"price",999999);assertEquals(5,p.crafting.materials.get("iron"));assertEquals(before+4*price,p.col);
  world.leave(p.id);var next=new GameWorld(world.data,store,(id,e)->{},now::get).profiles.get(p.hash);assertEquals(5,next.crafting.materials.get("iron"));assertEquals(p.col,next.col);assertEquals(p.crafting.lastGatherEvent,next.crafting.lastGatherEvent);
 }
 @Test void materialSalesRejectOversellingFractionalNegativeAndOverflowingQuantities()throws Exception{
  var p=player("warrior");station(p,"merchant");int count=p.crafting.materials.get("iron"),col=p.col;
  for(Object quantity:List.of(0,-1,1.5,100001,2147483648L,count+1))assertThrows(IllegalArgumentException.class,()->cmd(p,"shopSellMaterial","materialId","iron","quantity",quantity));
  assertThrows(IllegalArgumentException.class,()->cmd(p,"shopSellMaterial","materialId","fake","quantity",1));assertEquals(count,p.crafting.materials.get("iron"));assertEquals(col,p.col);
  cmd(p,"shopSellMaterial","materialId","iron","quantity",count);assertEquals(0,p.crafting.materials.get("iron"));int earned=p.col;assertThrows(IllegalArgumentException.class,()->cmd(p,"shopSellMaterial","materialId","iron","quantity",count));assertEquals(earned,p.col);
 }
 @Test void marketRequiresMerchantNoCombatEnabledRulesAndCurrencyCapacity()throws Exception{
  var p=player("warrior");int count=p.crafting.materials.get("iron");p.x=0;p.z=-55;assertThrows(IllegalArgumentException.class,()->cmd(p,"shopSellMaterial","materialId","iron","quantity",1));
  station(p,"merchant");p.pvp.combatUntil=now.get()+1000;assertThrows(IllegalArgumentException.class,()->cmd(p,"shopSellMaterial","materialId","iron","quantity",1));p.pvp.combatUntil=0;
  world.data.crafting.enabled=false;assertThrows(IllegalArgumentException.class,()->cmd(p,"shopSellMaterial","materialId","iron","quantity",1));world.data.crafting.enabled=true;
  p.col=10000000;assertThrows(IllegalArgumentException.class,()->cmd(p,"shopSellMaterial","materialId","iron","quantity",1));assertEquals(count,p.crafting.materials.get("iron"));assertEquals(10000000,p.col);
 }
 @Test void rootCanSetPricesDisableSalesAndCannotCreateBuySellArbitrage()throws Exception{
  var p=player("warrior");station(p,"merchant");var rules=world.data.crafting;var original=rules.materials.stream().filter(m->m.id().equals("iron")).findFirst().orElseThrow();int index=rules.materials.indexOf(original);
  rules.materials.set(index,new Crafting.Material("iron",original.name(),original.price(),0));assertThrows(IllegalArgumentException.class,()->cmd(p,"shopSellMaterial","materialId","iron","quantity",1));
  rules.materials.set(index,new Crafting.Material("iron",original.name(),original.price(),1));int col=p.col;cmd(p,"shopSellMaterial","materialId","iron","quantity",2);assertEquals(col+2,p.col);
  rules.materials.set(index,new Crafting.Material("iron",original.name(),original.price(),original.price()+1));assertThrows(IllegalArgumentException.class,world.data::validateAndGenerate);
 }
 @Test void failedSaleSaveRestoresBothBagAndCoins()throws Exception{
  var p=player("warrior");station(p,"merchant");int count=p.crafting.materials.get("iron"),col=p.col;store.save(p.profile());Path file=dir.resolve("players").resolve(p.id+".json");byte[] original=Files.readAllBytes(file);Files.delete(file);Files.createDirectory(file);
  try{assertThrows(IllegalArgumentException.class,()->cmd(p,"shopSellMaterial","materialId","iron","quantity",1));assertEquals(count,p.crafting.materials.get("iron"));assertEquals(col,p.col);}
  finally{Files.delete(file);Files.write(file,original);}
 }

 @Test void basicMarketCoversClassesClothesAndWeaponsWithoutMakingFreeCraftingProgress()throws Exception{
  var p=player("warrior");var rules=world.data.crafting;assertEquals(28,rules.shopProducts.size());assertTrue(rules.shopProducts.stream().anyMatch(v->v.kind().equals("armor")));assertTrue(rules.shopProducts.stream().anyMatch(v->v.slot().equals("offHand")));
  for(var resource:world.data.gathering.resources){var material=rules.materials.stream().filter(m->m.id().equals(resource.materialId())).findFirst().orElseThrow();assertTrue(Crafting.materialSalePrice(rules,material)>0,"Todo recurso recolectable se compra en la semilla");}
  var product=rules.shopProducts.stream().filter(v->v.kind().equals("weapon")&&v.slot().equals("mainHand")&&Crafting.compatible(Crafting.buyProduct(rules,p.catalog,v),p)).findFirst().orElseThrow();
  station(p,"merchant");var materials=new LinkedHashMap<>(p.crafting.materials);var xp=new LinkedHashMap<>(p.crafting.professionXp);int before=p.col;cmd(p,"shopBuyEquipment","productId",product.id(),"price",0,"quantity",999);
  assertEquals(before-product.price(),p.col);assertEquals(1,p.crafting.items.size());assertEquals(materials,p.crafting.materials);assertEquals(xp,p.crafting.professionXp);var item=p.crafting.items.values().iterator().next();assertEquals(product.price(),item.investedCol);
  p.x=world.data.floor(1).spawn.x();p.z=world.data.floor(1).spawn.z();cmd(p,"craftEquip","itemId",item.id,"slot","mainHand");assertEquals(item.id,p.crafting.equipped.get("mainHand"));station(p,"merchant");assertThrows(IllegalArgumentException.class,()->cmd(p,"shopSell","itemId",item.id));
  p.x=world.data.floor(1).spawn.x();p.z=world.data.floor(1).spawn.z();cmd(p,"craftUnequip","slot","mainHand");world.leave(p.id);var recovered=new GameWorld(world.data,store,(id,e)->{},now::get).profiles.get(p.hash);assertTrue(recovered.crafting.items.containsKey(item.id));assertEquals(p.col,recovered.col);
 }
 @Test void boughtClothesKeepGenderClassAndLevelRestrictionsAndCanBeResoldOnce()throws Exception{
  var p=player("healer");station(p,"merchant");var product=world.data.crafting.shopProducts.stream().filter(v->v.kind().equals("armor")&&Crafting.compatible(Crafting.buyProduct(world.data.crafting,p.catalog,v),p)).findFirst().orElseThrow();int col=p.col;
  cmd(p,"shopBuyEquipment","productId",product.id());var item=p.crafting.items.values().iterator().next();assertEquals("female",item.gender);assertEquals("healer",item.classId);p.x=world.data.floor(1).spawn.x();p.z=world.data.floor(1).spawn.z();cmd(p,"craftEquip","itemId",item.id,"slot","armor");assertEquals(item.id,p.crafting.equipped.get("armor"));cmd(p,"craftUnequip","slot","armor");station(p,"merchant");cmd(p,"shopSell","itemId",item.id);assertEquals(col-product.price()+(int)Math.floor(product.price()*world.data.crafting.saleMultiplier),p.col);assertThrows(IllegalArgumentException.class,()->cmd(p,"shopSell","itemId",item.id));
 }
 @Test void unavailableUnusableAndUnaffordableProductsNeverChargeOrGrantAnItem()throws Exception{
  var p=player("warrior");station(p,"merchant");var rules=world.data.crafting;var good=rules.shopProducts.stream().filter(v->Crafting.compatible(Crafting.buyProduct(rules,p.catalog,v),p)).findFirst().orElseThrow();var bad=rules.shopProducts.stream().filter(v->!Crafting.compatible(Crafting.buyProduct(rules,p.catalog,v),p)).findFirst().orElseThrow();int before=p.col;
  assertThrows(IllegalArgumentException.class,()->cmd(p,"shopBuyEquipment","productId",bad.id()));assertEquals(before,p.col);assertTrue(p.crafting.items.isEmpty());p.col=0;assertThrows(IllegalArgumentException.class,()->cmd(p,"shopBuyEquipment","productId",good.id()));p.col=before;
  rules.shopProducts.replaceAll(v->v.id().equals(good.id())?new Crafting.Product(v.id(),v.name(),v.kind(),v.targetId(),v.slot(),v.price(),false):v);assertThrows(IllegalArgumentException.class,()->cmd(p,"shopBuyEquipment","productId",good.id()));assertThrows(IllegalArgumentException.class,()->cmd(p,"shopBuyEquipment","productId","inventado"));assertTrue(p.crafting.items.isEmpty());assertEquals(before,p.col);
 }
 @Test void emptyMarketIsPreservedAndBadProductsAreRejectedDuringWorldValidation()throws Exception{
  var rules=world.data.crafting;rules.shopProducts=new ArrayList<>();world.data.validateAndGenerate();assertTrue(rules.shopProducts.isEmpty());rules.shopProducts=null;world.data.validateAndGenerate();assertFalse(rules.shopProducts.isEmpty());
  rules.shopProducts.add(new Crafting.Product("bad-stock","Arma inexistente","weapon","does-not-exist","mainHand",10,true));assertThrows(IllegalArgumentException.class,world.data::validateAndGenerate);
 }

}
