package dev.aincrad;
import com.fasterxml.jackson.databind.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import static org.junit.jupiter.api.Assertions.*;
import java.nio.file.*;
import java.util.*;

class GameWorldTest {
 @TempDir Path dir;ObjectMapper json=new ObjectMapper();PlayerStore store;GameWorld world;List<Map<String,Object>> events=new ArrayList<>();
 @BeforeEach void setup()throws Exception{store=new PlayerStore(dir,json);world=new GameWorld(WorldData.load(Path.of("../world/world.json"),json),store,(id,e)->events.add(e));}
 @AfterEach void close()throws Exception{store.close();}
 GameWorld.Player player()throws Exception{var w=world.join("Explorador","");return world.online.get(w.get("id"));}
 void command(GameWorld.Player p,String command)throws Exception{world.command(p.id,json.readTree(command));}
 void tick(int count){for(int i=0;i<count;i++)world.tick(.05);}
 @Test void deterministicWorldAndDifferentSeed()throws Exception{var original=world.data;var copy=WorldData.load(Path.of("../world/world.json"),json);assertEquals(original.floor(1).props,copy.floor(1).props);copy.seed++;copy.validateAndGenerate();assertNotEquals(original.floor(1).props,copy.floor(1).props);}
 @Test void keyboardNormalizesDiagonalAndExpires()throws Exception{var p=player();double x=p.x,z=p.z;command(p,"{\"type\":\"input\",\"seq\":1,\"dx\":1,\"dz\":-1}");tick(4);assertEquals(GameWorld.SPEED*.2,Math.hypot(p.x-x,p.z-z),.0001);tick(20);double stopped=p.x;tick(20);assertEquals(stopped,p.x);command(p,"{\"type\":\"input\",\"seq\":0,\"dx\":-1,\"dz\":0}");tick(2);assertEquals(stopped,p.x);}
 @Test void clicksDoNotTeleportAndInputsCannotSupplyStats()throws Exception{var p=player();double z=p.z;command(p,"{\"type\":\"move\",\"x\":0,\"z\":-30,\"hp\":999,\"col\":10000}");tick(20);assertEquals(5.5,z-p.z,.001);assertEquals(0,p.col);assertEquals(100,p.hp);assertThrows(IllegalArgumentException.class,()->command(p,"{\"type\":\"move\",\"x\":99999,\"z\":0}"));assertThrows(IllegalArgumentException.class,()->command(p,"{\"type\":\"input\",\"dx\":\"NaN\",\"dz\":0}"));assertFalse(world.data.walkable(1,10,19));}
 @Test void attackRangeCooldownDeathAndRespawn()throws Exception{var p=player();var m=world.monsters.get("boar-1");p.target=m.id;command(p,"{\"type\":\"attack\"}");assertEquals(48,m.hp);p.x=m.x;p.z=m.z-2;command(p,"{\"type\":\"attack\"}");assertEquals(29,m.hp);command(p,"{\"type\":\"attack\"}");assertEquals(29,m.hp);tick(14);command(p,"{\"type\":\"attack\",\"skill\":true}");assertEquals(0,m.hp);assertEquals(30,p.xp);assertEquals(16,p.col);int xp=p.xp;command(p,"{\"type\":\"attack\"}");assertEquals(xp,p.xp);spawnSafe(p);tick(370);assertEquals(48,m.hp);}
 void spawnSafe(GameWorld.Player p){p.x=0;p.z=16;}
 @Test void questRewardIsGrantedExactlyOnce()throws Exception{var p=player();p.x=3;p.z=13;command(p,"{\"type\":\"interact\"}");assertTrue(p.quest);p.kills=3;command(p,"{\"type\":\"interact\"}");assertEquals(60,p.col);assertEquals(7,p.potions);command(p,"{\"type\":\"interact\"}");assertEquals(60,p.col);assertEquals(40,p.xp);}
 @Test void portalRequiresBossAndProximity()throws Exception{var p=player();p.unlocked=true;command(p,"{\"type\":\"portal\"}");assertEquals(1,p.floor);var portal=world.data.floor(1).portal;p.x=portal.x();p.z=portal.z();p.unlocked=false;command(p,"{\"type\":\"portal\"}");assertEquals(1,p.floor);p.unlocked=true;command(p,"{\"type\":\"portal\"}");assertEquals(2,p.floor);assertEquals(world.data.floor(2).spawn.z(),p.z);}
 @Test void profileResumesBySecretAndNeverByName()throws Exception{var welcome=world.join("Rodolfo","");String token=(String)welcome.get("token");var p=world.online.get(welcome.get("id"));p.col=42;p.weapon=2;world.leave(p.id);var next=new GameWorld(world.data,store,(id,e)->{});var resumed=next.join("Otro nombre",token);assertEquals(p.id,resumed.get("id"));assertEquals(42,next.online.get(p.id).col);String disk=Files.readString(dir.resolve(p.id+".json"));assertFalse(disk.contains(token));assertThrows(IllegalArgumentException.class,()->next.join("Rodolfo",token));assertThrows(IllegalArgumentException.class,()->next.join("Rodolfo","inventado"));assertTrue(Files.list(dir).noneMatch(f->f.toString().endsWith(".partial")));}
 @Test void aiContextRequiresARealNearbyNpc()throws Exception{var p=player();assertThrows(IllegalArgumentException.class,()->world.npcContext(p.id,"inventado"));p.x=3;p.z=13;assertEquals("Lyra",world.npcContext(p.id,"lyra").get("name"));p.z=-30;assertThrows(IllegalArgumentException.class,()->world.npcContext(p.id,"lyra"));}
 @Test void worldRejectsInvalidPortalAndBlockedSpawn()throws Exception{var copy=WorldData.load(Path.of("../world/world.json"),json);copy.floor(1).portal=new WorldData.Portal(0,0,999,false);assertThrows(IllegalArgumentException.class,copy::validateAndGenerate);copy=WorldData.load(Path.of("../world/world.json"),json);copy.floor(1).spawn=new WorldData.Point(10,19);assertThrows(IllegalArgumentException.class,copy::validateAndGenerate);}
 @Test void appearanceAndClassAreAuthoritativeAndPersisted()throws Exception{var appearance=new WorldData.Appearance("female","kind","#c39757","#dfb18b","healer","elf");var welcome=world.join("Lyren","",appearance);var p=world.online.get(welcome.get("id"));assertEquals(110,p.hp);assertEquals(5.2,p.profession.speed());assertEquals(appearance,p.appearance);world.leave(p.id);assertEquals(appearance,store.load().get(0).appearance());assertThrows(IllegalArgumentException.class,()->world.join("Fake","",new WorldData.Appearance("female","kind","url(invalid)","#ffffff","admin","elf")));}
 @Test void selfEditorCannotModifyExperienceOrAnotherPlayer()throws Exception{var a=player();var b=player();String cmd="{\"type\":\"profile\",\"name\":\"Renombrado\",\"id\":\""+b.id+"\",\"xp\":9000,\"col\":9000,\"appearance\":{\"gender\":\"female\",\"face\":\"kind\",\"hairColor\":\"#74503a\",\"skinColor\":\"#bb835d\",\"classId\":\"healer\",\"race\":\"elf\"}}";command(a,cmd);assertEquals("Renombrado",a.name);assertEquals("Explorador",b.name);assertEquals(0,a.xp);assertEquals(0,a.col);assertEquals(100,a.hp);assertEquals(110,a.maxHp());a.x=0;a.z=-30;assertThrows(IllegalArgumentException.class,()->command(a,cmd));}
 @Test void rootEditsOfflineProfilesAndKeepsBackup()throws Exception{var p=player();world.leave(p.id);world.updateCharacter(p.id,"Editado",p.appearance,150,77,8,true);assertEquals(2,p.level());assertEquals(77,p.col);assertEquals("Editado",store.load().get(0).name());assertTrue(Files.list(dir.getParent().resolve("backups")).anyMatch(f->f.toString().contains(p.id)));}

 @Test void equipmentUnlocksByClassGenderAndLevel()throws Exception{var p=player();assertEquals(1,p.outfit().minLevel());p.xp=400;assertEquals(5,p.outfit().minLevel());assertEquals("warrior",p.outfit().classId());assertEquals(175,p.maxHp());assertEquals(34,p.damage());assertEquals(4,p.defense());p.appearance=new WorldData.Appearance("female","calm","#342f32","#dfb18b","warrior","human");assertEquals("female",p.outfit().gender());p.xp=900;assertEquals(10,p.outfit().minLevel());assertEquals(12,p.critical());}
 @Test void customAttributeCanHaveRealEffectOrBeDescriptive()throws Exception{var p=player();var definitions=new ArrayList<>(world.data.characterOptions.attributeDefinitions);definitions.add(new WorldData.AttributeDefinition("strength","Fuerza","damage",0,50,1));definitions.add(new WorldData.AttributeDefinition("rarity","Rareza","none",0,10,1));world.data.characterOptions.attributeDefinitions=definitions;p.outfit().attributes().put("strength",9.0);p.outfit().attributes().put("rarity",7.0);world.data.validateAndGenerate();assertEquals(28,p.damage());assertEquals(100,p.maxHp());assertEquals(7.0,p.outfit().attributes().get("rarity"));}
 @Test void equipmentRangesAndRequiredStarterSetsAreEnforced()throws Exception{world.data.characterOptions.equipmentSets.get(0).attributes().put("defense",900.0);assertThrows(IllegalArgumentException.class,world.data::validateAndGenerate);world.data.characterOptions.equipmentSets.get(0).attributes().put("defense",1.0);world.data.characterOptions.equipmentSets.remove(0);assertThrows(IllegalArgumentException.class,world.data::validateAndGenerate);}


 @Test void pointsAreEarnedSpentAndPersistedWithEffects()throws Exception{var p=player();p.xp=200;int hp=p.hp;command(p,"{\"type\":\"progression\",\"attributes\":{\"vitality\":3,\"power\":2},\"talents\":{\"warrior-discipline\":1,\"warrior-guard\":1}}");assertEquals(145,p.maxHp());assertEquals(27,p.damage());assertEquals(1,p.view().get("attributePoints"));assertEquals(0,p.view().get("talentPoints"));assertEquals(hp,p.hp);world.leave(p.id);var next=new GameWorld(world.data,store,(id,e)->{});assertEquals(3,next.profiles.get(p.hash).attributeRanks.get("vitality"));assertEquals(1,next.profiles.get(p.hash).talentRanks.get("warrior-guard"));}
 @Test void cannotForgePointsPrerequisitesOrAnotherClassTree()throws Exception{var p=player();p.xp=200;assertThrows(IllegalArgumentException.class,()->command(p,"{\"type\":\"progression\",\"xp\":9999,\"attributes\":{\"vitality\":99},\"talents\":{}}"));assertThrows(IllegalArgumentException.class,()->command(p,"{\"type\":\"progression\",\"attributes\":{},\"talents\":{\"warrior-guard\":1}}"));assertThrows(IllegalArgumentException.class,()->command(p,"{\"type\":\"progression\",\"attributes\":{},\"talents\":{\"mage-focus\":1}}"));assertThrows(IllegalArgumentException.class,()->command(p,"{\"type\":\"progression\",\"attributes\":{\"power\":1.5},\"talents\":{}}"));assertEquals(200,p.xp);assertTrue(p.attributeRanks.isEmpty());}
 @Test void respecAndClassChangesRefundWithoutHealingAndRespectPolicy()throws Exception{var p=player();p.xp=200;command(p,"{\"type\":\"progression\",\"attributes\":{\"vitality\":1},\"talents\":{\"warrior-discipline\":1}}");p.hp=50;world.data.characterOptions.progression.allowRespec=false;assertThrows(IllegalArgumentException.class,()->command(p,"{\"type\":\"progression\",\"attributes\":{},\"talents\":{}}"));world.data.characterOptions.progression.allowRespec=true;var a=new WorldData.Appearance("male","calm","#342f32","#dfb18b","mage","human");world.updateCharacter(p.id,p.name,a,null,null,null,false);assertTrue(p.talentRanks.isEmpty());assertEquals(1,p.attributeRanks.get("vitality"));assertEquals(50,p.hp);assertEquals(2,p.view().get("talentPoints"));}
 @Test void levelGainAutomaticallyAwardsUnspentPoints()throws Exception{var p=player();p.xp=90;var m=world.monsters.get("boar-1");m.hp=1;p.x=m.x;p.z=m.z-2;p.target=m.id;command(p,"{\"type\":\"attack\"}");assertEquals(2,p.level());assertEquals(3,p.view().get("attributePoints"));assertEquals(1,p.view().get("talentPoints"));}
 @Test void mageHasRealRangedDamageAndHealerRestoresNearbyAllies()throws Exception{var p=player();var m=world.monsters.get("boar-1");p.x=m.x;p.z=m.z-9;p.target=m.id;command(p,"{\"type\":\"attack\"}");assertEquals(48,m.hp);var mage=new WorldData.Appearance("male","calm","#342f32","#dfb18b","mage","human");world.updateCharacter(p.id,p.name,mage,null,null,null,true);command(p,"{\"type\":\"attack\"}");assertEquals(31,m.hp);var h=world.join("Sanador","",new WorldData.Appearance("female","calm","#342f32","#dfb18b","healer","human"));var healer=world.online.get(h.get("id"));spawnSafe(p);healer.x=p.x;healer.z=p.z;p.hp=30;healer.hp=50;m.participants.add(p.id);m.x=p.x+4;m.z=p.z;command(healer,"{\"type\":\"attack\",\"skill\":true}");assertEquals(66,p.hp);assertEquals(86,healer.hp);assertTrue(m.participants.contains(healer.id));command(healer,"{\"type\":\"attack\",\"skill\":true}");assertEquals(66,p.hp);assertTrue(events.stream().anyMatch(e->e.get("type").equals("heal")));}
 @Test void rootCanAllocateOfflineAndFailureKeepsOldProfile()throws Exception{var p=player();world.leave(p.id);var build=new Progression.Build(Map.of("power",3),Map.of("warrior-discipline",1));world.updateCharacter(p.id,p.name,p.appearance,100,80,8,true,build);assertEquals(26,p.damage());assertEquals(3,store.load().get(0).attributeRanks().get("power"));assertThrows(IllegalArgumentException.class,()->world.updateCharacter(p.id,"Cambio",p.appearance,0,0,0,true,build));assertEquals("Explorador",p.name);assertEquals(80,p.col);}
 @Test void progressionTreesRejectCyclesAndUnknownEffects()throws Exception{var rules=world.data.characterOptions.progression;var first=rules.talents.get(0);rules.talents.set(0,new Progression.Talent(first.id(),first.classId(),first.name(),first.description(),first.branch(),first.minLevel(),first.maxRank(),first.cost(),List.of(first.id()),first.effects()));assertThrows(IllegalArgumentException.class,world.data::validateAndGenerate);rules.talents.set(0,first);rules.attributes.get(0).effects().put("executeShell",1.0);assertThrows(IllegalArgumentException.class,world.data::validateAndGenerate);}
 @Test void worldReconfigurationReturnsInvalidBuildPoints()throws Exception{var p=player();p.xp=100;command(p,"{\"type\":\"progression\",\"attributes\":{\"power\":3},\"talents\":{\"warrior-discipline\":1}}");world.leave(p.id);world.data.characterOptions.progression.attributePointsPerLevel=1;var next=new GameWorld(world.data,store,(id,e)->{});var reloaded=next.profiles.get(p.hash);assertEquals(2,reloaded.level());assertTrue(reloaded.attributeRanks.isEmpty());assertEquals(1,reloaded.view().get("attributePoints"));}
}
