package dev.aincrad;

import com.fasterxml.jackson.databind.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import static org.junit.jupiter.api.Assertions.*;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.atomic.AtomicLong;

class RacesWeaponsPvpTest {
 @TempDir Path dir;ObjectMapper json=new ObjectMapper();PlayerStore store;GameWorld world;AtomicLong now=new AtomicLong(2_000_000_000_000L);
 @BeforeEach void setup()throws Exception{store=new PlayerStore(dir.resolve("players"),json);world=new GameWorld(WorldData.load(Path.of("../world/world.json"),json),store,(id,e)->{},now::get);}
 @AfterEach void close()throws Exception{store.close();}
 GameWorld.Player create(String race,String cls)throws Exception{var a=new WorldData.Appearance("female","kind","#342f32","#dfb18b",cls,race);var joined=world.join("Aventurero","",a);return world.online.get(joined.get("id"));}
 void cmd(GameWorld.Player p,String payload)throws Exception{world.command(p.id,json.readTree(payload));}
 void target(GameWorld.Player a,GameWorld.Player b)throws Exception{cmd(a,"{\"type\":\"target\",\"kind\":\"player\",\"id\":\""+b.id+"\"}");}
 void field(GameWorld.Player... players){for(int i=0;i<players.length;i++){players[i].x=0;players[i].z=-6-i;players[i].pvp.spawnProtectedUntil=0;players[i].pvpMode=true;}}
 void hit(GameWorld.Player a,GameWorld.Player b)throws Exception{target(a,b);a.attackAt=0;cmd(a,"{\"type\":\"attack\"}");}
 @Test void fiveRacesHaveRealPassivesAndPersist()throws Exception{
  assertEquals(List.of("human","dwarf","elf","darkelf","draconian"),world.data.characterOptions.races.stream().map(r->r.id).toList());
  var human=create("human","warrior");var dwarf=create("dwarf","warrior");var elf=create("elf","warrior");var dark=create("darkelf","warrior");var dragon=create("draconian","warrior");
  assertEquals(human.maxHp()+15,dwarf.maxHp());assertEquals(human.defense()+1,dwarf.defense());assertEquals(2,elf.critical());assertEquals(human.maxHp()-5,dark.maxHp());assertEquals(human.damage()+1,dragon.damage());world.leave(dragon.id);assertEquals("draconian",store.load().stream().filter(p->p.id().equals(dragon.id)).findFirst().orElseThrow().appearance().race());
 }
 @Test void healingRacialCooldownCannotBeResetByRejoinOrRestart()throws Exception{var p=create("human","healer");p.hp=30;cmd(p,"{\"type\":\"racial\"}");assertEquals(50,p.hp);cmd(p,"{\"type\":\"racial\"}");assertEquals(50,p.hp);world.leave(p.id);var next=new GameWorld(world.data,store,(id,e)->{},now::get);assertEquals(now.get()+30000,next.profiles.get(p.hash).pvp.racialReadyAt);}
 @Test void dwarfShieldAbsorbsPvpAndRacialFlameFollowsPvpRules()throws Exception{var dwarf=create("dwarf","warrior");var dragon=create("draconian","warrior");field(dwarf,dragon);cmd(dwarf,"{\"type\":\"racial\"}");assertEquals(30,dwarf.racialShield);int hp=dwarf.hp;target(dragon,dwarf);cmd(dragon,"{\"type\":\"racial\"}");assertEquals(hp,dwarf.hp);assertTrue(dwarf.racialShield<30);assertTrue(dwarf.pvp.combatUntil>now.get());dragon.pvp.racialReadyAt=0;dwarf.z=16;assertThrows(IllegalArgumentException.class,()->cmd(dragon,"{\"type\":\"racial\"}"));}
 @Test void elvenBuffExpiresOnServerTick()throws Exception{var p=create("elf","mage");double speed=p.speed();cmd(p,"{\"type\":\"racial\"}");assertEquals(speed+2,p.speed());for(int i=0;i<110;i++)world.tick(.05);assertEquals(speed,p.speed());}
 @Test void healerWandsMageStaffsAndDualSlotsUnlockByLevel()throws Exception{assertEquals(30,world.data.characterOptions.weaponSets.size());var p=create("human","healer");assertEquals("wand",p.weapons().mainHand().kind());assertEquals("wand",p.weapons().offHand().kind());world.equip(p.id,"healer-santuario-1",false);assertEquals("shield",p.weapons().offHand().kind());assertThrows(IllegalArgumentException.class,()->world.equip(p.id,"healer-liturgia-10",false));assertThrows(IllegalArgumentException.class,()->world.equip(p.id,"mage-astral-1",false));p.xp=400;world.equip(p.id,"healer-liturgia-5",false);assertEquals("tome",p.weapons().offHand().kind());assertTrue(p.modifier("healing")>=4);world.leave(p.id);assertEquals("healer-liturgia-5",new GameWorld(world.data,store,(id,e)->{},now::get).profiles.get(p.hash).weaponSetId);var mage=create("human","mage");assertEquals(2,mage.weapons().mainHand().hands());assertNull(mage.weapons().offHand());world.equip(mage.id,"mage-canalizador-1",false);assertEquals(1,mage.weapons().mainHand().hands());assertEquals("wand",mage.weapons().offHand().kind());}
 @Test void twoHandAndInvalidWeaponAttributesAreRejected()throws Exception{var c=world.data.characterOptions;var set=c.weaponSets.stream().filter(w->w.mainHand().hands()==2).findFirst().orElseThrow();var shield=c.weaponSets.get(0).offHand();int i=c.weaponSets.indexOf(set);c.weaponSets.set(i,new Weapons.Loadout(set.id(),set.name(),set.classId(),1,set.autoEquip(),set.mainHand(),shield));assertThrows(IllegalArgumentException.class,world.data::validateAndGenerate);c.weaponSets.set(i,set);set.mainHand().attributes().put("executeShell",1.0);assertThrows(IllegalArgumentException.class,world.data::validateAndGenerate);}
 @Test void safeZonesSpawnProtectionDisabledModeAndRangeAreEnforced()throws Exception{var a=create("human","warrior");var b=create("human","warrior");target(a,b);assertThrows(IllegalArgumentException.class,()->hit(a,b));a.pvpMode=true;assertThrows(IllegalArgumentException.class,()->hit(a,b));field(a,b);b.pvp.spawnProtectedUntil=now.get()+5000;assertThrows(IllegalArgumentException.class,()->hit(a,b));b.pvp.spawnProtectedUntil=0;b.z=-20;int hp=b.hp;hit(a,b);assertEquals(hp,b.hp);b.z=a.z-1;world.data.pvp.enabled=false;assertThrows(IllegalArgumentException.class,()->hit(a,b));world.data.pvp.enabled=true;hit(a,b);assertTrue(b.hp<hp);}
 @Test void unjustKillLosesCitizenshipAndMarksMurdererWithoutXpReward()throws Exception{var a=create("human","warrior");var b=create("human","mage");field(a,b);b.hp=1;hit(a,b);assertEquals(0,b.hp);assertEquals(75,a.pvp.citizenship);assertEquals(1,a.pvp.murders);assertTrue(a.pvp.murderer(world.data.pvp,now.get()));assertEquals(1,b.pvp.deaths);assertEquals(0,a.xp);assertEquals(0,a.col);assertEquals(1,store.journal().receipts().size());}
 @Test void selfDefenseDoesNotGiveTheInitialAttackerARightToKill()throws Exception{var a=create("human","warrior");var b=create("human","warrior");field(a,b);hit(a,b);assertTrue(Pvp.justified(b.pvp,a.id,a.pvp,world.data.pvp,now.get()));hit(b,a);assertFalse(Pvp.justified(a.pvp,b.id,b.pvp,world.data.pvp,now.get()));b.hp=1;hit(a,b);assertEquals(75,a.pvp.citizenship);assertEquals(100,b.pvp.citizenship);}
 @Test void defensiveKillHasNoPenaltyAndExpiredDefenseDoes()throws Exception{var a=create("human","warrior");var b=create("human","warrior");field(a,b);hit(a,b);a.hp=1;hit(b,a);assertEquals(100,b.pvp.citizenship);assertEquals(0,b.pvp.murders);assertEquals(1,b.pvp.kills);var c=create("human","warrior");field(b,c);hit(c,b);now.addAndGet(61000);c.hp=1;hit(b,c);assertEquals(75,b.pvp.citizenship);}
 @Test void combatDisconnectLeavesAttackableBodyAndRestartKeepsTag()throws Exception{var a=create("human","warrior");var b=create("human","warrior");field(a,b);hit(a,b);world.leave(b.id);assertFalse(b.online);assertTrue(world.online.containsKey(b.id));int hp=b.hp;hit(a,b);assertTrue(b.hp<hp);var next=new GameWorld(world.data,store,(id,e)->{},now::get);assertTrue(next.online.containsKey(b.id));assertFalse(next.online.get(b.id).online);now.addAndGet(21000);world.tick(.05);assertFalse(world.online.containsKey(b.id));}
 @Test void killReceiptRepairsProfilesAfterPartialWriteCrash()throws Exception{var a=create("human","warrior");var b=create("human","warrior");field(a,b);var oldA=a.profile();var oldB=b.profile();b.hp=1;hit(a,b);store.save(oldA);store.save(oldB);var next=new GameWorld(world.data,store,(id,e)->{},now::get);assertEquals(75,next.profiles.get(a.hash).pvp.citizenship);assertEquals(1,next.profiles.get(b.hash).pvp.deaths);assertEquals(1,next.profiles.get(a.hash).pvp.lastEvent);next.saveAll();var again=new GameWorld(world.data,store,(id,e)->{},now::get);assertEquals(1,again.profiles.get(a.hash).pvp.murders);}
 @Test void noEquipPortalOrSelfEditInCombatAndClientCannotForgeCivicStats()throws Exception{var a=create("human","warrior");var b=create("human","warrior");field(a,b);hit(a,b);a.x=0;a.z=16;assertThrows(IllegalArgumentException.class,()->world.equip(a.id,"warrior-duelista-1",false));assertThrows(IllegalArgumentException.class,()->cmd(a,"{\"type\":\"portal\"}"));assertThrows(IllegalArgumentException.class,()->world.updateCharacter(a.id,a.name,a.appearance,null,null,null,false));cmd(a,"{\"type\":\"pvpMode\",\"enabled\":false,\"citizenship\":9999,\"murders\":0}");assertEquals(100,a.pvp.citizenship);assertTrue(a.pvp.combatUntil>now.get());}
 @Test void healerCannotAccidentallyHealOpposingCombatants()throws Exception{var h=create("human","healer");var b=create("human","warrior");field(h,b);hit(b,h);h.hp=20;b.hp=20;cmd(h,"{\"type\":\"attack\",\"skill\":true}");assertTrue(h.hp>20);assertEquals(20,b.hp);}
 @Test void rootPardonAndPaidRedemptionPersistWithoutErasingHistory()throws Exception{var a=create("human","warrior");var b=create("human","warrior");field(a,b);b.hp=1;hit(a,b);a.pvp.combatUntil=0;a.x=3;a.z=13;a.col=300;cmd(a,"{\"type\":\"redeem\"}");assertEquals(80,a.pvp.citizenship);assertEquals(200,a.col);assertTrue(a.pvp.murderer(world.data.pvp,now.get()));assertThrows(IllegalArgumentException.class,()->cmd(a,"{\"type\":\"redeem\"}"));world.citizenship(a.id,100,true);assertFalse(a.pvp.murderer(world.data.pvp,now.get()));assertEquals(1,a.pvp.murders);assertEquals(100,store.load().stream().filter(p->p.id().equals(a.id)).findFirst().orElseThrow().pvp().citizenship);assertTrue(Files.list(dir.resolve("backups")).findAny().isPresent());}
 @Test void migrationPreservesLegacyRaceCustomValuesAndProfiles()throws Exception{var raw=(com.fasterxml.jackson.databind.node.ObjectNode)json.readTree(Path.of("../world/world.json").toFile());raw.remove(List.of("schemaRevision","pvp"));var c=(com.fasterxml.jackson.databind.node.ObjectNode)raw.get("characterOptions");c.remove("weaponSets");var r=c.putArray("races");r.addObject().put("id","human").put("name","Humano propio").put("description","Historia propia").put("scale",1.05).put("ears","round");r.addObject().put("id","cait").put("name","Cait").put("description","Legado").put("scale",.95).put("ears","cat");Path file=dir.resolve("legacy.json");json.writeValue(file.toFile(),raw);var migrated=WorldData.load(file,json);assertEquals(6,migrated.characterOptions.races.size());assertEquals("Humano propio",migrated.characterOptions.races.get(0).name);assertEquals(1.05,migrated.characterOptions.races.get(0).scale);assertEquals("cat",migrated.characterOptions.races.get(1).model);assertEquals(30,migrated.characterOptions.weaponSets.size());assertTrue(Files.list(dir).anyMatch(p->p.toString().endsWith(".bak")));var player=create("human","warrior");var profile=(com.fasterxml.jackson.databind.node.ObjectNode)json.valueToTree(player.profile());profile.remove(List.of("pvp","weaponSetId"));json.writeValue(dir.resolve("players").resolve(player.id+".json").toFile(),profile);var loaded=new GameWorld(migrated,store,(id,e)->{},now::get).profiles.get(player.hash);assertEquals(100,loaded.pvp.citizenship);assertEquals("",loaded.weaponSetId);assertEquals(player.appearance,loaded.appearance);}
}
