package dev.aincrad;

import com.fasterxml.jackson.databind.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import static org.junit.jupiter.api.Assertions.*;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.atomic.AtomicLong;

class SkillsSpecializationsTest {
 @TempDir Path dir;ObjectMapper json=new ObjectMapper();PlayerStore store;GameWorld world;AtomicLong now=new AtomicLong(2_000_000_000_000L);
 @BeforeEach void setup()throws Exception{store=new PlayerStore(dir.resolve("players"),json);world=new GameWorld(WorldData.load(Path.of("../world/world.json"),json),store,(id,e)->{},now::get);}
 @AfterEach void close()throws Exception{store.close();}
 GameWorld.Player player(String cls,String spec)throws Exception{var w=world.join("Aprendiz","",new WorldData.Appearance("female","calm","#342f32","#dfb18b",cls,"human",spec));var p=world.online.get(w.get("id"));p.xp=1000;return p;}
 void cmd(GameWorld.Player p,String type,Object... f){var n=json.createObjectNode().put("type",type);for(int i=0;i<f.length;i+=2)n.set((String)f[i],json.valueToTree(f[i+1]));world.command(p.id,n);}
 void learn(GameWorld.Player p,String id){var s=p.catalog.skills.stream().filter(a->a.id().equals(id)).findFirst().orElseThrow();addParents(p,s.talentId());cmd(p,"progression","attributes",p.attributeRanks,"talents",p.talentRanks);}
 void addParents(GameWorld.Player p,String id){var t=p.catalog.progression.talents.stream().filter(a->a.id().equals(id)).findFirst().orElseThrow();for(String before:t.requires())addParents(p,before);p.talentRanks.put(id,1);}
 GameWorld.Monster target(GameWorld.Player p){var m=world.monsters.get("boar-1");p.x=0;p.z=-6;m.x=4;m.z=-6;m.hp=2000;p.target=m.id;p.targetKind="monster";return m;}
 void advance(long ms){now.addAndGet(ms);world.tick(.05);}
 @Test void threeWarriorSpecialtiesEnforceDistinctWeaponsAndArmor()throws Exception{var sword=player("warrior","swordsman");var assassin=player("warrior","assassin");var tank=player("warrior","tank");assertEquals("mail",sword.outfit().style());assertEquals("sword",sword.weapons().mainHand().kind());assertEquals("leather",assassin.outfit().style());assertEquals("dagger",assassin.weapons().mainHand().kind());assertEquals("dagger",assassin.weapons().offHand().kind());assertEquals("plate",tank.outfit().style());assertEquals("shield",tank.weapons().offHand().kind());assertEquals("Ciudadano",assassin.pvp.status(world.data.pvp,now.get()));assertThrows(IllegalArgumentException.class,()->world.equip(sword.id,"warrior-guardia-1",false));assertThrows(IllegalArgumentException.class,()->world.equip(tank.id,"warrior-vanguardia-1",false));assertEquals(8,world.data.characterOptions.specializations.size());assertEquals(33,world.data.characterOptions.skills.size());}
 @Test void allFourMageElementsHaveBranchesAndSharedSummons()throws Exception{for(String id:List.of("fire","ice","water","earth")){var p=player("mage",id);assertEquals("staff",p.weapons().mainHand().kind());assertTrue(p.catalog.skills.stream().anyMatch(s->Specializations.permits(s.specializationIds(),id)&&s.element().equals(id)));learn(p,"summon-sprite");assertTrue(((List<?>)((Map<?,?>)p.view().get("skills")).get("learned")).contains("summon-sprite"));}}
 @Test void cannotLearnOtherSpecializationOrCastUnlearnedSkill()throws Exception{var p=player("mage","fire");assertThrows(IllegalArgumentException.class,()->cmd(p,"castSkill","skillId","fire-bolt"));assertThrows(IllegalArgumentException.class,()->cmd(p,"progression","attributes",Map.of(),"talents",Map.of("learn-ice-lance",1)));assertThrows(IllegalArgumentException.class,()->world.updateCharacter(p.id,p.name,new WorldData.Appearance("female","calm","#342f32","#dfb18b","warrior","human","fire"),null,null,null,true));}
 @Test void specialtyChangeRefundsTreeWithoutHealingAndRespecRuleIsEnforced()throws Exception{var p=player("mage","fire");learn(p,"fire-bolt");p.hp=30;var ice=new WorldData.Appearance("female","calm","#342f32","#dfb18b","mage","human","ice");world.data.characterOptions.progression.allowRespec=false;assertThrows(IllegalArgumentException.class,()->world.updateCharacter(p.id,p.name,ice,null,null,null,false));world.data.characterOptions.progression.allowRespec=true;world.updateCharacter(p.id,p.name,ice,null,null,null,false);assertEquals(30,p.hp);assertTrue(p.talentRanks.isEmpty());assertEquals("ice",p.appearance.specializationId());}
 @Test void individualDamageRespectsRangeAndCooldownPersists()throws Exception{var p=player("mage","fire");learn(p,"fire-bolt");var m=target(p);m.x=20;cmd(p,"castSkill","skillId","fire-bolt");assertEquals(2000,m.hp);m.x=5;cmd(p,"castSkill","skillId","fire-bolt");assertTrue(m.hp<2000);int hp=m.hp;cmd(p,"castSkill","skillId","fire-bolt");assertEquals(hp,m.hp);world.leave(p.id);var next=new GameWorld(world.data,store,(id,e)->{},now::get).profiles.get(p.hash);assertTrue(next.skills.readyAt.get("fire-bolt")>now.get());}
 @Test void areaDamageHitsNearbyCreaturesButNeverUnselectedPlayers()throws Exception{var p=player("mage","fire");learn(p,"fire-storm");var m=target(p);var near=world.monsters.get("boar-2");near.x=6;near.z=-6;near.hp=2000;var far=world.monsters.get("boar-3");far.x=15;far.z=-6;far.hp=2000;var other=player("warrior","tank");other.x=6;other.z=-6;int hp=other.hp;cmd(p,"castSkill","skillId","fire-storm");assertTrue(m.hp<2000);assertTrue(near.hp<2000);assertEquals(2000,far.hp);assertEquals(hp,other.hp);}
 @Test void healerSingleTargetAndAreaHealingAreDifferent()throws Exception{var h=player("healer","healer");var a=player("warrior","swordsman");var b=player("warrior","tank");learn(h,"healer-chorus");h.hp=30;a.hp=30;b.hp=30;a.x=2;a.z=16;b.x=7;b.z=16;cmd(h,"target","kind","player","id",a.id);cmd(h,"castSkill","skillId","healer-mend");assertTrue(a.hp>30);assertEquals(30,h.hp);assertEquals(30,b.hp);a.hp=30;cmd(h,"castSkill","skillId","healer-chorus");assertTrue(h.hp>30);assertTrue(a.hp>30);assertEquals(30,b.hp);}
 @Test void cursesReduceStatsAndExpireAndAreaBuffsReachNearbyAllies()throws Exception{var h=player("healer","healer");learn(h,"healer-weakness");learn(h,"healer-haste");var a=player("warrior","tank");h.x=0;h.z=-6;a.x=0;a.z=-7;h.pvpMode=true;h.pvp.spawnProtectedUntil=a.pvp.spawnProtectedUntil=0;int damage=a.damage();cmd(h,"target","kind","player","id",a.id);cmd(h,"castSkill","skillId","healer-weakness");assertEquals(damage-4,a.damage());advance(8100);assertEquals(damage,a.damage());h.pvp.combatUntil=a.pvp.combatUntil=0;double speed=a.speed();cmd(h,"castSkill","skillId","healer-haste");assertEquals(speed+1,a.speed(),.001);advance(8100);assertEquals(speed,a.speed(),.001);}
 @Test void curseLethalTickRegistersPvPCitizenshipExactlyOnce()throws Exception{var h=player("healer","healer");learn(h,"healer-decay");var a=player("mage","ice");h.x=0;h.z=-6;a.x=0;a.z=-7;h.pvpMode=true;h.pvp.spawnProtectedUntil=a.pvp.spawnProtectedUntil=0;a.hp=2;cmd(h,"target","kind","player","id",a.id);cmd(h,"castSkill","skillId","healer-decay");assertEquals(1,a.hp);advance(1100);assertEquals(0,a.hp);assertEquals(75,h.pvp.citizenship);assertEquals(1,h.pvp.murders);advance(1100);assertEquals(1,h.pvp.murders);}
 @Test void summonsAttackSelectedMonstersAndExpireWithoutAttackingPlayers()throws Exception{var p=player("mage","earth");learn(p,"summon-sprite");var m=target(p);cmd(p,"castSkill","skillId","summon-sprite");assertEquals(1,((List<?>)world.snapshot(p.id).get("summons")).size());advance(100);assertTrue(m.hp<2000);var other=player("mage","fire");other.x=1;other.z=-6;int hp=other.hp;cmd(p,"target","kind","player","id",other.id);advance(1600);assertEquals(hp,other.hp);advance(21000);assertTrue(((List<?>)world.snapshot(p.id).get("summons")).isEmpty());}
 @Test void tankProvocationRedirectsCreatureWithoutControllingPlayers()throws Exception{var tank=player("warrior","tank");learn(tank,"tank-taunt");var other=player("warrior","swordsman");var m=world.monsters.get("boar-1");m.x=m.homeX=3;m.z=m.homeZ=16;other.x=3;other.z=15;tank.x=0;tank.z=16;cmd(tank,"castSkill","skillId","tank-taunt");assertEquals(tank.id,m.tauntedBy);advance(50);assertTrue(m.x<3);assertEquals(3,other.x);}
 @Test void learnedSkillBarPersistsAndUnknownBindingsFail()throws Exception{var p=player("mage","water");learn(p,"water-flow");cmd(p,"bindSkill","slot",3,"skillId","water-wave");assertEquals("water-wave",Skills.slots(p).get(3));assertThrows(IllegalArgumentException.class,()->cmd(p,"bindSkill","slot",1,"skillId","fire-bolt"));world.leave(p.id);var loaded=new GameWorld(world.data,store,(id,e)->{},now::get).profiles.get(p.hash);assertEquals("water-wave",Skills.slots(loaded).get(3));}
}
