import {Component,Input,ViewChild,ElementRef,AfterViewInit,OnDestroy} from '@angular/core';
import {MonsterPreview} from './world-renderer.js';
import {FormsModule} from '@angular/forms';
@Component({selector:'bestiary-config',standalone:true,imports:[FormsModule],template:`
<section class="editor-card bestiary-config"><span class="eyebrow gold">TERRITORIOS · DIFICULTAD · POBLACIÓN</span><h2>Zonas de monstruos por nivel</h2><p class="muted">Piso {{floor.id}}. Los rangos recomiendan dificultad; no bloquean la entrada. La población se genera con la semilla, fuera de obstáculos y zonas protegidas.</p><button class="primary" (click)="addZone()">Añadir zona de monstruos</button>
@for(z of floor.monsterZones;track z.id;let i=$index){<details class="config-node" [open]="i===0"><summary>{{z.name}} · Nv. {{z.minLevel}}–{{z.maxLevel}} · {{z.population}} criaturas</summary><div class="field-row"><label>Nombre de la zona<input [(ngModel)]="z.name" maxlength="80"></label><label>Especie de la zona<select [(ngModel)]="z.speciesId">@for(s of world.monsterSpecies;track s.id){<option [value]="s.id">{{s.name}}</option>}</select></label></div><div class="effect-fields">@for(f of zoneFields;track f.id){<label>{{f.name}}<input type="number" [min]="f.min" [max]="f.max" [(ngModel)]="z[f.id]"></label>}</div><button (click)="floor.monsterZones.splice(i,1)">Eliminar zona</button><small>ID: {{z.id}}</small></details>}
<p class="muted">Hasta 12 zonas, 30 criaturas por zona y 200 criaturas totales por piso. Evita solapar zonas entre sí, refugio, patio o portal. Guardar valida también que exista espacio para todos los puntos de aparición.</p></section>
<section class="editor-card species-config"><span class="eyebrow gold">BESTIARIO CONFIGURABLE</span><h2>Especies y crecimiento</h2><label>Especie a editar<select aria-label="Especie a editar" [(ngModel)]="index">@for(s of world.monsterSpecies;track s.id;let i=$index){<option [ngValue]="i">{{s.name}}</option>}</select></label><div class="toolbar-actions"><button (click)="addSpecies()">Añadir especie</button><button (click)="removeSpecies()" [disabled]="world.monsterSpecies.length<=1">Eliminar especie</button></div>
<canvas #previewCanvas class="monster-preview" aria-label="Vista previa 3D de especie"></canvas>@if(species();as s){<div class="field-row"><label>Nombre de especie<input [(ngModel)]="s.name" maxlength="80"></label><label>Modelo 3D<select aria-label="Modelo 3D" [(ngModel)]="s.model">@for(m of models;track m.id){<option [value]="m.id">{{m.name}}</option>}</select></label><label>Color de especie<input type="color" [(ngModel)]="s.color"></label></div><p class="muted">Valor al nivel N = base + crecimiento × (N − 1), sujeto a los límites de la simulación. Los cambios se aplican al guardar y recargar el mundo.</p><div class="effect-fields">@for(f of speciesFields;track f.id){<label>{{f.name}}<input type="number" [step]="f.step||1" [min]="f.min" [max]="f.max" [(ngModel)]="s[f.id]"></label>}</div><label class="check"><input type="checkbox" [(ngModel)]="s.unlockPortal"> Su derrota desbloquea los portales que requieren jefe</label><h3>Materiales por derrota</h3><div class="effect-fields">@for(m of world.crafting.materials;track m.id){<label>{{m.name}}<input type="number" min="0" max="100000" [ngModel]="world.crafting.monsterDrops[s.id]?.[m.id]||0" (ngModelChange)="drop(s.id,m.id,$event)"></label>}</div><small>ID: {{s.id}}. Para eliminar una especie, retira antes sus zonas y apariciones manuales.</small>}
</section>`})
export class BestiaryConfigComponent implements AfterViewInit,OnDestroy {
 @ViewChild('previewCanvas') canvas?:ElementRef<HTMLCanvasElement>;preview?:MonsterPreview;
 ngAfterViewInit(){if(this.canvas)this.preview=new MonsterPreview(this.canvas.nativeElement,()=>this.species());}
 ngOnDestroy(){this.preview?.dispose();}
 @Input() world:any;@Input() floor:any;index=0;
 models=[{id:'slime',name:'Slime'},{id:'dog',name:'Perro'},{id:'goblin',name:'Trasgo'},{id:'orc',name:'Orco'},{id:'troll',name:'Troll'},{id:'boar',name:'Jabalí'},{id:'guardian',name:'Centinela'}];
 zoneFields=[{id:'minLevel',name:'Nivel mínimo',min:1,max:1000},{id:'maxLevel',name:'Nivel máximo',min:1,max:1000},{id:'x',name:'Centro de zona X',min:-100,max:100},{id:'z',name:'Centro de zona Z',min:-100,max:100},{id:'radius',name:'Radio de zona',min:3,max:18},{id:'population',name:'Población de zona',min:1,max:30},{id:'respawnSeconds',name:'Reaparición de zona (s)',min:1,max:86400}];
 speciesFields:any[]=[['baseHp','Vida base',1,50000],['hpPerLevel','Vida por nivel',0,2000],['baseDamage','Daño base',1,250,.1],['damagePerLevel','Daño por nivel',0,30,.1],['baseDefense','Defensa base',0,100,.1],['defensePerLevel','Defensa por nivel',0,5,.1],['speed','Velocidad de criatura',.3,6,.1],['attackRange','Alcance de ataque',1,6,.1],['aggroRange','Radio de detección',2,20,.1],['leashRange','Límite de persecución',2,35,.1],['attackCooldown','Intervalo de ataque (s)',.5,30,.1],['windupSeconds','Aviso de golpe (s)',0,5,.1],['baseXp','EXP base',0,10000],['xpPerLevel','EXP por nivel',0,1000],['baseCol','Col base',0,100000],['colPerLevel','Col por nivel',0,10000],['respawnSeconds','Reaparición individual (s)',1,86400]].map(([id,name,min,max,step])=>({id,name,min,max,step}));
 species(){return this.world?.monsterSpecies?.[this.index];}
 addZone(){this.floor.monsterZones??=[];this.floor.monsterZones.push({id:'zone-'+crypto.randomUUID().slice(0,8),name:'Nueva zona',speciesId:this.world.monsterSpecies.find((s:any)=>s.model==='slime')?.id||this.world.monsterSpecies[0].id,minLevel:1,maxLevel:3,x:0,z:0,radius:5,population:4,respawnSeconds:20});}
 addSpecies(){const s=structuredClone(this.species()||this.world.monsterSpecies[0]);s.id='species-'+crypto.randomUUID().slice(0,8);s.name='Nueva especie';this.world.monsterSpecies.push(s);this.index=this.world.monsterSpecies.length-1;}
 removeSpecies(){const s=this.species();if(!s||this.world.monsterSpecies.length<=1)return;delete this.world.crafting.monsterDrops[s.id];this.world.monsterSpecies.splice(this.index,1);this.index=0;}
 drop(id:string,material:string,n:number){this.world.crafting.monsterDrops[id]??={};if(n===0)delete this.world.crafting.monsterDrops[id][material];else this.world.crafting.monsterDrops[id][material]=n;}
}
