import { Component, Input } from '@angular/core';
import { FormsModule } from '@angular/forms';
@Component({selector:'crafting-config',standalone:true,imports:[FormsModule],template:`
@if(rules){<section class="editor-card crafting-config" id="crafting-config"><span class="eyebrow gold">RECETAS · MATERIALES · MEJORAS</span><h2>Herrería, sastrería y tienda</h2><label class="check"><input type="checkbox" [(ngModel)]="rules.enabled"> Activar talleres y tienda</label>
<div class="effect-fields">@for(f of fields;track f.id){<label>{{f.name}}<input type="number" [step]="f.step||1" [(ngModel)]="rules[f.id]"></label>}</div>
<h3>Oficios</h3>@for(p of rules.professions;track p.id){<div class="field-row"><label>Nombre<input [(ngModel)]="p.name"></label><label>Encargado<select [(ngModel)]="p.stationRole"><option value="smith">Herrero</option><option value="tailor">Sastre</option><option value="merchant">Mercader</option><option value="mine">Yacimiento</option><option value="forest">Árbol maderable</option></select></label><label>Descripción<input [(ngModel)]="p.description"></label></div>}
<h3>Materiales, precios y botín</h3><div class="table-scroll"><table><thead><tr><th>Material</th><th>Compra</th><th>Venta / unidad</th><th>Al crear personaje</th><th>Jabalí</th><th>Centinela</th></tr></thead><tbody>@for(m of rules.materials;track m.id){<tr><td><input [(ngModel)]="m.name"></td><td><input type="number" min="1" max="100000" [(ngModel)]="m.price" [attr.aria-label]="'Compra de '+m.name"></td><td><input type="number" min="0" [max]="m.price" [(ngModel)]="m.sellPrice" [attr.aria-label]="'Venta de '+m.name" placeholder="Auto"></td><td><input type="number" min="0" [ngModel]="rules.initialMaterials[m.id]||0" (ngModelChange)="cost(rules.initialMaterials,m.id,$event)"></td><td><input type="number" min="0" [ngModel]="rules.monsterDrops.boar?.[m.id]||0" (ngModelChange)="drop('boar',m.id,$event)"></td><td><input type="number" min="0" [ngModel]="rules.monsterDrops.guardian?.[m.id]||0" (ngModelChange)="drop('guardian',m.id,$event)"></td></tr>}</tbody></table></div>
<p class="muted">Venta vacía: se aplica la fracción de reventa. Cero: el mercado no compra ese material. El precio de venta no puede superar al de compra.</p><section class="market-config"><div class="binding-heading"><h3>Equipo en venta ({{rules.shopProducts?.length||0}})</h3><button (click)="addProduct()">+ Añadir producto</button></div><label>Producto<select [(ngModel)]="productIndex" aria-label="Producto del mercado">@for(p of rules.shopProducts;track p.id;let i=$index){<option [ngValue]="i">{{p.name}} · {{p.price}} col</option>}</select></label>@if(product();as p){<label class="check"><input type="checkbox" [(ngModel)]="p.enabled"> Disponible en el mercado</label><div class="field-row"><label>Nombre<input [(ngModel)]="p.name" maxlength="160" aria-label="Nombre del producto"></label><label>Precio<input type="number" min="1" max="1000000" [(ngModel)]="p.price" aria-label="Precio del producto"></label></div><div class="field-row"><label>Tipo<select [(ngModel)]="p.kind" (ngModelChange)="productKindChanged()"><option value="weapon">Arma / escudo / foco</option><option value="armor">Ropa / armadura</option></select></label><label>Conjunto<select [(ngModel)]="p.targetId" (ngModelChange)="productTargetChanged()">@for(t of productTargets();track t.id){<option [value]="t.id">{{t.name}}</option>}</select></label><label>Parte<select [(ngModel)]="p.slot">@if(p.kind==='armor'){<option value="armor">Ropa / armadura</option>}@else{<option value="mainHand">Principal</option>@if(productTarget()?.offHand){<option value="offHand">Secundaria / escudo</option>}}</select></label></div><small>Clase, género, nivel y atributos proceden del conjunto. Se vende una pieza por compra. Vaciar la lista cierra la venta de equipo sin afectar materiales.</small><button (click)="removeProduct()">Retirar producto del catálogo</button>}</section>
<div class="binding-heading"><h3>Recetas ({{rules.recipes.length}})</h3><button (click)="add()">+ Añadir receta</button></div>
<label>Receta<select aria-label="Receta a editar" [(ngModel)]="index">@for(r of rules.recipes;track r.id;let i=$index){<option [ngValue]="i">{{r.name}}</option>}</select></label>
@if(recipe();as r){<div class="field-row"><label>Nombre<input [(ngModel)]="r.name" maxlength="160"></label><label>Oficio<select [(ngModel)]="r.professionId">@for(p of recipeJobs();track p.id){<option [value]="p.id">{{p.name}}</option>}</select></label></div>
<div class="field-row"><label>Producto<select [(ngModel)]="r.kind" (ngModelChange)="kindChanged()"><option value="weapon">Arma / escudo / foco</option><option value="armor">Ropa / armadura</option></select></label><label>Plantilla<select [(ngModel)]="r.targetId" (ngModelChange)="targetChanged()">@for(t of targets();track t.id){<option [value]="t.id">{{t.name}}</option>}</select></label><label>Parte<select [(ngModel)]="r.slot">@if(r.kind==='armor'){<option value="armor">Conjunto de ropa / armadura</option>}@else{<option value="mainHand">Principal</option>@if(target()?.offHand){<option value="offHand">Secundaria</option>}}</select></label></div>
<div class="effect-fields">@for(f of recipeFields;track f.id){<label>{{f.name}}<input type="number" [(ngModel)]="r[f.id]"></label>}</div>
<div class="weapon-editor-grid">@for(group of costGroups;track group.id){<div><h3>{{group.name}}</h3>@for(m of rules.materials;track m.id){<label>{{m.name}}<input type="number" min="0" [ngModel]="r[group.id][m.id]||0" (ngModelChange)="cost(r[group.id],m.id,$event)"></label>}</div>}</div>
<div class="weapon-editor-grid">@for(group of bonuses;track group.id){<div><h3>{{group.name}}</h3>@for(a of catalog.attributeDefinitions;track a.id){<label>{{a.name}}<input type="number" step=".1" min="-100" max="100" [ngModel]="r[group.id][a.id]||0" (ngModelChange)="r[group.id][a.id]=$event"></label>}</div>}</div>
<p class="muted">Cada mejora cobra el coste base × rango nuevo. Requiere nivel de oficio ≥ nivel de receta + rango actual. Los atributos respetan sus límites y no curan al equipar. La venta devuelve una fracción del col pagado al taller; no reembolsa materiales.</p><button (click)="remove()">Eliminar receta</button>
}</section>}`})
export class CraftingConfigComponent{
 @Input() rules:any;@Input() catalog:any;index=0;productIndex=0;
 fields=[{id:'maxInventory',name:'Objetos por personaje'},{id:'maxProfessionLevel',name:'Nivel máximo de oficio'},{id:'xpPerLevel',name:'EXP por nivel de oficio'},{id:'upgradeExperience',name:'EXP por mejora'},{id:'stationRange',name:'Alcance del taller',step:.5},{id:'potionPrice',name:'Precio de poción'},{id:'saleMultiplier',name:'Fracción de reventa (0–1)',step:.05}];
 recipeFields=[{id:'minProfessionLevel',name:'Nivel mínimo de oficio'},{id:'experience',name:'EXP por creación'},{id:'colCost',name:'Col por creación'},{id:'maxUpgrade',name:'Mejora máxima'},{id:'upgradeColCost',name:'Col base por mejora'}];costGroups=[{id:'materials',name:'Materiales para crear'},{id:'upgradeMaterials',name:'Materiales base para mejorar'}];bonuses=[{id:'bonusAttributes',name:'Bonificación al crear'},{id:'upgradeAttributes',name:'Atributos por mejora'}];
 product(){return this.rules.shopProducts?.[this.productIndex];}
 productTargets(){return this.product()?.kind==='armor'?this.catalog.equipmentSets:this.catalog.weaponSets;}
 productTarget(){return this.productTargets()?.find((t:any)=>t.id===this.product()?.targetId);}
 productTargetChanged(){const p=this.product();p.slot=p.kind==='armor'?'armor':'mainHand';}
 productKindChanged(){this.product().targetId=this.productTargets()[0].id;this.productTargetChanged();}
 addProduct(){this.rules.shopProducts??=[];const template=this.catalog.weaponSets[0];this.rules.shopProducts.push({id:'product-'+crypto.randomUUID().slice(0,8),name:'Nuevo producto',kind:'weapon',targetId:template.id,slot:'mainHand',price:55,enabled:true});this.productIndex=this.rules.shopProducts.length-1;}
 removeProduct(){this.rules.shopProducts.splice(this.productIndex,1);this.productIndex=0;}
 recipeJobs(){return this.rules.professions.filter((p:any)=>!['mine','forest'].includes(p.stationRole));}
 recipe(){return this.rules?.recipes[this.index];}targets(){return this.recipe()?.kind==='armor'?this.catalog.equipmentSets:this.catalog.weaponSets;}target(){return this.targets().find((t:any)=>t.id===this.recipe().targetId);}
 targetChanged(){this.recipe().slot=this.recipe().kind==='armor'?'armor':'mainHand';}kindChanged(){this.recipe().targetId=this.targets()[0].id;this.targetChanged();}
 cost(map:any,id:string,value:number){if(value===0)delete map[id];else map[id]=value;}drop(kind:string,id:string,value:number){this.rules.monsterDrops[kind]??={};this.cost(this.rules.monsterDrops[kind],id,value);}
 add(){const r=this.recipe()?structuredClone(this.recipe()):{professionId:this.rules.professions[0].id,kind:'weapon',targetId:this.catalog.weaponSets[0].id,slot:'mainHand',minProfessionLevel:1,colCost:10,materials:{},experience:25,maxUpgrade:5,upgradeColCost:15,upgradeMaterials:{},bonusAttributes:{},upgradeAttributes:{}};r.id='recipe-'+crypto.randomUUID().slice(0,8);r.name='Nueva receta';this.rules.recipes.push(r);this.index=this.rules.recipes.length-1;}
 remove(){this.rules.recipes.splice(this.index,1);this.index=0;}
}
