import { specialty, permits, weaponFits, armorFits } from './equipment.mjs';
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { FormsModule } from '@angular/forms';
@Component({selector:'crafting-panel',standalone:true,imports:[FormsModule],template:`
@if(me?.crafting&&world?.crafting;as ignored){
<h2>{{mode==='shop'?'Mercado de suministros':mode==='bag'?'Bolsa del personaje':'Oficios y talleres'}}</h2>
<p class="muted">{{mode==='shop'?'Compra suministros o vende materiales y equipo al mercader.':mode==='bag'?'Aquí se guardan tus metales, maderas y botín. Acércate al mercader para venderlos.':'Crea equipo, gana experiencia de oficio y mejora tus propias piezas. Puedes aprender los cuatro oficios.'}}</p>
@if(!world.crafting.enabled){<p class="error">Los talleres están desactivados.</p>}
@if(mode==='crafting'){<div class="material-bag">@for(m of world.crafting.materials;track m.id){<span><b>{{me.crafting.materials[m.id]||0}}</b>{{m.name}}</span>}<span><b>{{me.col}}</b>Col</span></div>}
@if(mode==='shop'){
<p class="station-hint">{{station('merchant')?.name||'Mercader'}} · {{near('merchant')?'A tu alcance':'Acércate a la tienda'}}</p>
<button (click)="go('merchant')" [disabled]="!station('merchant')">Ir a la tienda</button>
<label>Unidades por compra<input type="number" min="1" max="50" [(ngModel)]="quantity" aria-label="Cantidad de compra"></label>
<div class="shop-products">@for(m of world.crafting.materials;track m.id){<button [disabled]="!near('merchant')||me.col<m.price*quantity" (click)="send('shopBuy',{materialId:m.id,quantity})"><b>{{m.name}}</b><small>{{m.price}} col / unidad · Total {{m.price*quantity}}</small></button>}<button [disabled]="!near('merchant')||me.col<world.crafting.potionPrice*quantity" (click)="send('shopBuy',{materialId:'potion',quantity})"><b>Poción de vida</b><small>{{world.crafting.potionPrice}} col / unidad</small></button></div>
<section class="market-equipment"><h3>Armas, ropa y armaduras</h3><label class="check"><input type="checkbox" [(ngModel)]="onlyUsableProducts"> Sólo equipo para mi personaje</label><div class="market-product-list">@for(p of products();track p.id){@if(productSource(p);as t){<article [attr.data-product-id]="p.id"><span class="market-product-icon">{{p.kind==='armor'?'♜':p.slot==='offHand'?'◈':'⚔'}}</span><div><b>{{p.name}}</b><small>{{className(t.classId)}} · Nv. {{t.minLevel}}{{t.gender?' · '+genderName(t.gender):''}} · {{slotName(p.slot)}}</small><small>{{p.price}} col · pieza individual</small></div><button class="primary" [disabled]="!canBuyProduct(p)" (click)="send('shopBuyEquipment',{productId:p.id})" [attr.aria-label]="'Comprar '+p.name">Comprar</button></article>}}@empty{<p class="muted">No hay productos disponibles con este filtro.</p>}</div><small>Las compras se guardan en tu bolsa. Equipa en el refugio; las dos manos ocupan también la secundaria.</small></section>
}@else if(mode==='crafting'){
<div class="profession-tabs">@for(j of world.crafting.professions;track j.id){<button [class.selected]="profession===j.id" (click)="profession=j.id"><b>{{j.name}}</b><small>Nv. {{me.crafting.levels[j.id]||1}} · {{me.crafting.professionXp[j.id]||0}} EXP</small></button>}</div>
@if(job();as j){@if(j.stationRole==='mine'||j.stationRole==='forest'){<p class="muted">{{j.description}}</p><div class="gather-list">@for(n of resourceNodes();track n.id){<article><b>{{resource(n.typeId)?.name}}</b><small>Oficio Nv. {{resource(n.typeId)?.minProfessionLevel}} · {{resource(n.typeId)?.amount}} unidades · {{resource(n.typeId)?.experience}} EXP</small><small>{{n.available?'Disponible':('Regenera en '+Math.ceil(n.readyInSeconds)+' s')}} · {{distance(n)}} m</small><div><button (click)="approach(n)">Acercarse</button><button (click)="send('gather',{nodeId:n.id})" [disabled]="!canGather(n)">Recolectar</button></div></article>}@empty{<p class="muted">No hay recursos de este oficio en este piso.</p>}</div>}@else{<p class="muted">{{j.description}}</p><p class="station-hint">{{station(j.stationRole)?.name||'Sin encargado en este piso'}} · {{near(j.stationRole)?'A tu alcance':'Visita su taller'}}</p><button (click)="go(j.stationRole)" [disabled]="!station(j.stationRole)">Ir al taller</button>
<label class="check"><input type="checkbox" [(ngModel)]="onlyCompatible"> Mostrar recetas para mi clase y género</label>
<div class="recipe-list">@for(r of recipes();track r.id){<article><div><b>{{r.name}}</b><small>Oficio Nv. {{r.minProfessionLevel}} · {{r.experience}} EXP</small><small>{{costs(r.materials)}} · {{r.colCost}} col</small><small>Bonificación artesanal: {{attributes(r.bonusAttributes)}}</small></div><button (click)="send('craft',{recipeId:r.id})" [disabled]="!near(j.stationRole)||!canCraft(r)" [attr.aria-label]="'Crear '+r.name">Crear</button></article>}</div>}}
}
@if(mode==='shop'||mode==='bag'){
<section class="resource-bag"><div class="bag-heading"><h3>Bolsa de recursos</h3><span>{{me.col}} col</span></div><p class="station-hint">{{near('merchant')?'Puedes vender al mercader cercano.':'Acércate al mercado, fuera de combate, para vender.'}}</p>@if(mode==='bag'){<button (click)="go('merchant')" [disabled]="!station('merchant')">Ir al mercado</button>}
@for(m of bagMaterials();track m.id){<article [attr.data-material-id]="m.id"><div class="bag-material"><b>{{m.name}}</b><span>{{me.crafting.materials[m.id]}} unidades</span><small>{{materialPrice(m)>0?materialPrice(m)+' col por unidad':'El mercado no compra este material'}}</small></div><label [for]="'sell-'+m.id">Cantidad<input [id]="'sell-'+m.id" type="number" min="1" [max]="me.crafting.materials[m.id]" step="1" [ngModel]="saleQuantity(m.id)" (ngModelChange)="saleQuantities[m.id]=$event" [attr.aria-label]="'Cantidad a vender de '+m.name"></label><div class="bag-actions"><button class="primary" (click)="send('shopSellMaterial',{materialId:m.id,quantity:saleQuantity(m.id)})" [disabled]="!canSellMaterial(m)" [attr.aria-label]="'Vender '+m.name">Vender · {{materialTotal(m)}} col</button><button (click)="saleQuantities[m.id]=me.crafting.materials[m.id]" [attr.aria-label]="'Seleccionar todo '+m.name">Todo</button></div></article>}@empty{<p class="muted">Tu bolsa está vacía. Recolecta madera o minerales, o consigue botín de monstruos.</p>}
</section>}
<h3>Equipo en tu bolsa <small>{{me.crafting.items.length}} / {{me.crafting.capacity}}</small></h3>
<p class="muted">Equipa en el refugio. Mejorar aumenta atributos sin curarte. Las armas de dos manos ocupan ambas ranuras.</p>
@for(i of me.crafting.items;track i.id){<article class="crafted-item"><b>{{i.name}} +{{i.upgrade}}</b><small>{{className(i.classId)}} · Nv. {{i.minLevel}}{{i.gender?' · '+genderName(i.gender):''}} {{equipped(i)?'· EQUIPADO':''}}</small><small>{{attributes(i.weapon?.attributes||i.armor?.attributes)}}</small><div class="crafted-actions">
@if(i.armor){<button (click)="send('craftEquip',{itemId:i.id,slot:'armor'})" [disabled]="!compatible(i)">Vestir</button>}@else{
@if(!['shield','orb','tome'].includes(i.weapon.kind)){<button (click)="send('craftEquip',{itemId:i.id,slot:'mainHand'})" [disabled]="!compatible(i)">Principal</button>}
@if(i.weapon.hands===1){<button (click)="send('craftEquip',{itemId:i.id,slot:'offHand'})" [disabled]="!compatible(i)||me.weapons.mainHand.hands===2">Secundaria</button>}}
@for(slot of equippedSlots(i);track slot){<button (click)="send('craftUnequip',{slot})">Desequipar {{slotName(slot)}}</button>}
@if(mode==='shop'||mode==='bag'){<button (click)="send('shopSell',{itemId:i.id})" [disabled]="equipped(i)||!near('merchant')">Vender · {{sale(i)}} col</button>}
@else if(recipe(i);as r){<button (click)="send('craftUpgrade',{itemId:i.id})" [disabled]="!canUpgrade(i,r)">Mejorar a +{{i.upgrade+1}}</button><small>Mejora: {{r.upgradeColCost*(i.upgrade+1)}} col · {{costs(r.upgradeMaterials,i.upgrade+1)}} · máx. +{{r.maxUpgrade}}</small>}
</div></article>}@empty{<p class="muted">Compra equipo en el mercado o créalo en los talleres. Tu equipo inicial sigue disponible en Inventario.</p>}
}`})
export class CraftingPanelComponent{
 Math=Math;@Input() me:any;@Input() world:any;@Input() mode='crafting';@Input() nodes:any[]=[];@Input() gatherCooldown=0;@Output() action=new EventEmitter<any>();profession='blacksmith';quantity=1;onlyCompatible=true;onlyUsableProducts=true;saleQuantities:Record<string,number>={};
 productSource(p:any){return (p.kind==='weapon'?this.world.characterOptions.weaponSets:this.world.characterOptions.equipmentSets).find((t:any)=>t.id===p.targetId);}
 usableProduct(p:any){const t=this.productSource(p);return !!t&&t.minLevel<=this.me.level&&(p.kind==='weapon'?weaponFits(this.world.characterOptions,t,this.me.appearance):armorFits(this.world.characterOptions,t,this.me.appearance));}
 products(){return (this.world.crafting.shopProducts||[]).filter((p:any)=>p.enabled&&(!this.onlyUsableProducts||this.usableProduct(p)));}
 canBuyProduct(p:any){return this.near('merchant')&&this.usableProduct(p)&&this.me.col>=p.price&&this.me.crafting.items.length<this.world.crafting.maxInventory;}
 bagMaterials(){return this.world.crafting.materials.filter((m:any)=>(this.me.crafting.materials[m.id]||0)>0);}
 saleQuantity(id:string){return this.saleQuantities[id]??1;}
 materialPrice(m:any){return m.sellPrice!=null?m.sellPrice:this.world.crafting.saleMultiplier===0?0:Math.max(1,Math.floor(m.price*this.world.crafting.saleMultiplier));}
 materialTotal(m:any){const n=this.saleQuantity(m.id);return Number.isInteger(n)&&n>0?this.materialPrice(m)*n:0;}
 canSellMaterial(m:any){const n=this.saleQuantity(m.id);return this.near('merchant')&&Number.isInteger(n)&&n>=1&&n<=this.me.crafting.materials[m.id]&&this.materialPrice(m)>0&&this.me.col+this.materialTotal(m)<=10000000;}
 resource(id:string){return this.world.gathering.resources.find((r:any)=>r.id===id);}resourceNodes(){return this.nodes.filter(n=>this.resource(n.typeId)?.professionId===this.job()?.id);}
 distance(n:any){return Math.hypot(n.x-this.me.x,n.z-this.me.z).toFixed(1);}canGather(n:any){const r=this.resource(n.typeId);return this.world.gathering.enabled&&n.available&&this.gatherCooldown<=0&&this.me.pvp.combatSeconds<=0&&this.me.crafting.levels[r.professionId]>=r.minProfessionLevel&&Math.hypot(n.x-this.me.x,n.z-this.me.z)<=this.world.gathering.range;}
 approach(n:any){const f=this.world.floors.find((f:any)=>f.id===this.me.floor),dist=Math.min(this.world.gathering.range-.15,2);const candidates=[{x:n.x-dist,z:n.z},{x:n.x+dist,z:n.z},{x:n.x,z:n.z-dist},{x:n.x,z:n.z+dist}].filter(p=>Math.hypot(p.x,p.z)<f.radius-1&&!f.props.some((v:any)=>Math.hypot(p.x-v.x,p.z-v.z)<v.radius+.45)).sort((a,b)=>Math.hypot(a.x-this.me.x,a.z-this.me.z)-Math.hypot(b.x-this.me.x,b.z-this.me.z));if(candidates.length)this.send('move',candidates[0]);}
 send(type:string,extra:any){this.action.emit({type,...extra});}job(){return this.world.crafting.professions.find((j:any)=>j.id===this.profession)||this.world.crafting.professions[0];}
 station(role:string){return this.world.floors.find((f:any)=>f.id===this.me.floor)?.npcs.filter((n:any)=>n.role===role).sort((a:any,b:any)=>Math.hypot(a.x-this.me.x,a.z-this.me.z)-Math.hypot(b.x-this.me.x,b.z-this.me.z))[0];}
 near(role:string){const n=this.station(role);return this.world.crafting.enabled&&n&&this.me.hp>0&&this.me.pvp.combatSeconds<=0&&Math.hypot(n.x-this.me.x,n.z-this.me.z)<=this.world.crafting.stationRange;}
 go(role:string){const n=this.station(role);if(n)this.send('move',{x:n.x,z:n.z});}
 source(r:any){return (r.kind==='weapon'?this.world.characterOptions.weaponSets:this.world.characterOptions.equipmentSets).find((s:any)=>s.id===r.targetId);}
 recipes(){return this.world.crafting.recipes.filter((r:any)=>r.professionId===this.job()?.id&&(!this.onlyCompatible||(this.source(r)&&(r.kind==='weapon'?weaponFits(this.world.characterOptions,this.source(r),this.me.appearance):armorFits(this.world.characterOptions,this.source(r),this.me.appearance)))));}
 hasMaterials(cost:any,factor=1){return Object.entries(cost).every(([id,n])=>(this.me.crafting.materials[id]||0)>=Number(n)*factor);}
 canCraft(r:any){return this.me.crafting.items.length<this.world.crafting.maxInventory&&this.me.crafting.levels[r.professionId]>=r.minProfessionLevel&&this.me.col>=r.colCost&&this.hasMaterials(r.materials);}
 recipe(i:any){return this.world.crafting.recipes.find((r:any)=>r.id===i.recipeId);}
 canUpgrade(i:any,r:any){const job=this.world.crafting.professions.find((j:any)=>j.id===r.professionId);return this.near(job.stationRole)&&i.upgrade<r.maxUpgrade&&this.me.crafting.levels[r.professionId]>=Math.min(this.world.crafting.maxProfessionLevel,r.minProfessionLevel+i.upgrade)&&this.me.col>=r.upgradeColCost*(i.upgrade+1)&&this.hasMaterials(r.upgradeMaterials,i.upgrade+1);}
 costs(m:any,factor=1){return Object.entries(m||{}).map(([id,n])=>`${Number(n)*factor} ${this.world.crafting.materials.find((d:any)=>d.id===id)?.name||id}`).join(' · ')||'Sin materiales';}
 attributes(a:any){return Object.entries(a||{}).map(([id,n])=>`${this.world.characterOptions.attributeDefinitions.find((d:any)=>d.id===id)?.name||id}: ${n}`).join(' · ')||'Sin bonificación';}
 className(id:string){return this.world.characterOptions.classes.find((c:any)=>c.id===id)?.name||id;}genderName(id:string){return this.world.characterOptions.genders.find((c:any)=>c.id===id)?.name||id;}
 compatible(i:any){const s=specialty(this.world.characterOptions,this.me.appearance);return permits(i.specializationIds,s?.id)&&(!s||(i.weapon?s.weaponKinds.includes(i.weapon.kind):s.armorStyles.includes(i.armor.style)))&&i.classId===this.me.appearance.classId&&i.minLevel<=this.me.level&&(!i.gender||i.gender===this.me.appearance.gender);}
 equippedSlots(i:any){return Object.keys(this.me.crafting.equipped).filter(k=>this.me.crafting.equipped[k]===i.id);}equipped(i:any){return this.equippedSlots(i).length>0;}
 slotName(s:string){return s==='mainHand'?'principal':s==='offHand'?'secundaria':'ropa';}sale(i:any){return Math.floor((i.investedCol||0)*this.world.crafting.saleMultiplier);}
}
