import { Component, Input } from '@angular/core';
import { FormsModule } from '@angular/forms';
@Component({selector:'gathering-config',standalone:true,imports:[FormsModule],template:`
@if(world?.gathering){<section class="editor-card" id="gathering-config"><span class="eyebrow gold">MINERÍA · LEÑADOR</span><h2>Recursos del mundo</h2><label class="check"><input type="checkbox" [(ngModel)]="world.gathering.enabled"> Permitir recolección</label><div class="field-row"><label>Alcance de recolección<input type="number" step=".1" [(ngModel)]="world.gathering.range"></label><label>Espera entre acciones (s)<input type="number" step=".1" [(ngModel)]="world.gathering.cooldownSeconds"></label></div><p class="muted">Cada nodo es compartido: cuando alguien recolecta, todos esperan su regeneración. El agotamiento y la recompensa se conservan al reiniciar.</p>
<div class="binding-heading"><h3>Tipos de metal y madera</h3><button (click)="addType()">+ Añadir recurso</button></div>
@for(r of world.gathering.resources;track r.id){<details class="config-node"><summary>{{r.name}} · Nv. {{r.minProfessionLevel}}</summary><div class="field-row"><label>Nombre<input [(ngModel)]="r.name"></label><label>Oficio<select [(ngModel)]="r.professionId">@for(j of gatheringJobs();track j.id){<option [value]="j.id">{{j.name}}</option>}</select></label><label>Material<select [(ngModel)]="r.materialId">@for(m of world.crafting.materials;track m.id){<option [value]="m.id">{{m.name}}</option>}</select></label></div><div class="effect-fields"><label>Nivel de oficio<input type="number" [(ngModel)]="r.minProfessionLevel"></label><label>Unidades<input type="number" [(ngModel)]="r.amount"></label><label>EXP de oficio<input type="number" [(ngModel)]="r.experience"></label><label>Regeneración (s)<input type="number" [(ngModel)]="r.respawnSeconds"></label><label>Forma<select [(ngModel)]="r.kind"><option value="rock">Yacimiento</option><option value="tree">Árbol</option></select></label><label>Color<input type="color" [(ngModel)]="r.color"></label></div></details>}
<div class="binding-heading"><h3>Nodos del piso {{floor.id}}</h3><button (click)="addNode()" [disabled]="!world.gathering.resources.length">+ Colocar recurso</button></div><div class="table-scroll"><table><thead><tr><th>Tipo</th><th>X</th><th>Z</th><th></th></tr></thead><tbody>@for(n of floor.resources;track n.id;let i=$index){<tr><td><select [(ngModel)]="n.typeId">@for(r of world.gathering.resources;track r.id){<option [value]="r.id">{{r.name}}</option>}</select></td><td><input type="number" [(ngModel)]="n.x"></td><td><input type="number" [(ngModel)]="n.z"></td><td><button (click)="floor.resources.splice(i,1)" aria-label="Eliminar nodo">×</button></td></tr>}</tbody></table></div><p class="muted">Ubica los recursos separados de edificios, aparición, NPC y criaturas. Guardar y validar comprueba las colisiones.</p></section>}
`})
export class GatheringConfigComponent{
 @Input() world:any;@Input() floor:any;
 gatheringJobs(){return this.world.crafting.professions.filter((j:any)=>['mine','forest'].includes(j.stationRole));}
 addType(){this.world.gathering.resources.push({id:'resource-'+crypto.randomUUID().slice(0,8),name:'Nuevo recurso',professionId:this.gatheringJobs()[0].id,materialId:this.world.crafting.materials[0].id,minProfessionLevel:1,amount:2,experience:25,respawnSeconds:30,kind:'rock',color:'#92a8ad'});}
 addNode(){this.floor.resources.push({id:'node-'+crypto.randomUUID().slice(0,8),typeId:this.world.gathering.resources[0].id,x:-25,z:10});}
}
