import { Component, Input } from '@angular/core';
import { FormsModule } from '@angular/forms';
@Component({selector:'progression-config',standalone:true,imports:[FormsModule],template:`
@if(catalog?.progression){<section class="editor-card progression-config"><span class="eyebrow gold">REGLAS DE CRECIMIENTO</span><h2>Clases, atributos y árboles</h2><p class="muted">Configura los puntos que recibe cada nivel y los caminos de cada clase. Guarda y aplica el mundo para activar los cambios.</p>
<div class="field-row"><label>EXP por nivel<input type="number" min="1" max="10000" [(ngModel)]="catalog.progression.xpPerLevel"></label><label>Nivel máximo<input type="number" min="2" max="1000" [(ngModel)]="catalog.progression.maxLevel"></label><label>Atributos por nivel<input type="number" min="0" max="20" [(ngModel)]="catalog.progression.attributePointsPerLevel"></label><label>Talentos por nivel<input type="number" min="0" max="10" [(ngModel)]="catalog.progression.talentPointsPerLevel"></label></div><div class="field-row"><label>Vida automática por nivel<input type="number" min="0" max="50" [(ngModel)]="catalog.progression.hpPerLevel"></label><label>Daño automático por nivel<input type="number" min="0" max="10" [(ngModel)]="catalog.progression.damagePerLevel"></label></div><label class="check"><input type="checkbox" [(ngModel)]="catalog.progression.allowRespec"> Permitir redistribución y cambio de clase en el refugio</label>
<h3>Habilidades de clase</h3>@for(c of catalog.classes;track c.id){<details class="config-node"><summary>{{c.name}} · {{c.ability.name}}</summary><div class="field-row"><label>Nombre de habilidad<input [(ngModel)]="c.ability.name"></label><label>Tipo<select [(ngModel)]="c.ability.kind"><option value="strike">Golpe cuerpo a cuerpo</option><option value="arcane">Descarga a distancia</option><option value="heal">Curación de aliados en área</option></select></label></div><div class="field-row"><label>Alcance normal<input type="number" step="0.1" min="1" max="15" [(ngModel)]="c.attackRange"></label><label>Alcance de habilidad<input type="number" step="0.1" min="1" max="15" [(ngModel)]="c.ability.range"></label><label>{{c.ability.kind==='heal'?'Curación base':'Multiplicador de daño'}}<input type="number" step="0.1" [(ngModel)]="c.ability.power"></label><label>Enfriamiento (s)<input type="number" min="1" max="60" step="0.1" [(ngModel)]="c.ability.cooldown"></label></div></details>}
<header class="binding-heading"><h3>Atributos al subir nivel</h3><button (click)="addAttribute()">+ Nuevo atributo de personaje</button></header>
@for(a of catalog.progression.attributes;track a.id;let i=$index){<details class="config-node"><summary>{{a.name}} · {{a.id}}</summary><div class="field-row"><label>Nombre<input [(ngModel)]="a.name"></label><label>Rango máximo<input type="number" min="1" max="500" [(ngModel)]="a.maxRank"></label></div><label>Descripción<input [(ngModel)]="a.description" maxlength="300"></label><p class="muted">Efecto por punto invertido:</p><div class="effect-fields">@for(e of effectKeys;track e){<label>{{labels[e]}}<input type="number" step="0.01" [ngModel]="a.effects[e]||0" (ngModelChange)="setEffect(a,e,$event)"></label>}</div><button (click)="catalog.progression.attributes.splice(i,1)">Eliminar atributo</button></details>}
<header class="binding-heading"><h3>Árbol de talentos</h3><button (click)="addTalent()">+ Nuevo talento</button></header><label>Clase del árbol<select aria-label="Clase del árbol" [(ngModel)]="selectedClass">@for(c of catalog.classes;track c.id){<option [value]="c.id">{{c.name}}</option>}</select></label>
@for(t of catalog.progression.talents;track t.id;let i=$index){@if(t.classId===selectedClass){<details class="config-node"><summary>{{t.name}} · nivel {{t.minLevel}} · {{t.branch}}</summary><small>ID: {{t.id}}</small><div class="field-row"><label>Nombre<input [(ngModel)]="t.name"></label><label>Rama<input [(ngModel)]="t.branch"></label></div><label>Descripción<input [(ngModel)]="t.description" maxlength="300"></label><div class="field-row"><label>Nivel requerido<input type="number" min="2" [(ngModel)]="t.minLevel"></label><label>Rangos<input type="number" min="1" max="20" [(ngModel)]="t.maxRank"></label><label>Coste por rango<input type="number" min="1" max="20" [(ngModel)]="t.cost"></label></div><label>Especialidades (vacío: todas)<select multiple [(ngModel)]="t.specializationIds">@for(s of catalog.specializations;track s.id){@if(s.classId===t.classId){<option [value]="s.id">{{s.name}}</option>}}</select></label><label>Requisitos (IDs separados por coma)<input [ngModel]="t.requires.join(', ')" (ngModelChange)="setParents(t,$event)"></label><p class="muted">Se requiere un rango en cada predecesor. No se permiten ciclos ni enlaces a otra clase. Efectos por rango:</p><div class="effect-fields">@for(e of effectKeys;track e){<label>{{labels[e]}}<input type="number" step="0.01" [ngModel]="t.effects[e]||0" (ngModelChange)="setEffect(t,e,$event)"></label>}</div><button (click)="catalog.progression.talents.splice(i,1)">Eliminar talento</button></details>}}
<p class="muted">Si una nueva configuración invalida un reparto existente, el servidor devuelve sus puntos y conserva el nivel. Las estadísticas finales mantienen los límites de la simulación.</p></section>}
`})
export class ProgressionConfigComponent {
 @Input() catalog:any;selectedClass='warrior';
 effectKeys=['maxHp','damage','defense','speed','criticalChance','healing','skillPower','cooldownReduction'];labels:any={maxHp:'Vida máxima',damage:'Daño',defense:'Defensa',speed:'Velocidad',criticalChance:'Crítico (%)',healing:'Curación',skillPower:'Potencia (multiplicador)',cooldownReduction:'Recuperación (s)'};
 setEffect(node:any,e:string,value:number){if(value===0)delete node.effects[e];else node.effects[e]=value;}
 setParents(t:any,value:string){t.requires=value.split(',').map(v=>v.trim()).filter(Boolean);}
 addAttribute(){this.catalog.progression.attributes.push({id:'attribute-'+crypto.randomUUID().slice(0,8),name:'Nuevo atributo',description:'Define su efecto por punto.',maxRank:50,effects:{}});}
 addTalent(){this.catalog.progression.talents.push({id:'talent-'+crypto.randomUUID().slice(0,8),classId:this.selectedClass,name:'Nuevo talento',description:'Define un efecto por rango.',branch:'Nueva rama',minLevel:2,maxRank:3,cost:1,requires:[],effects:{},specializationIds:[]});}
}
