import { Component, Input } from '@angular/core';
import { FormsModule } from '@angular/forms';
@Component({selector:'pvp-config',standalone:true,imports:[FormsModule],template:`
@if(rules){<section class="editor-card" id="pvp-config"><span class="eyebrow gold">CONVIVENCIA Y CONSECUENCIAS</span><h2>PvP y ciudadanía</h2><p class="muted">El servidor decide cada golpe, baja y penalización. No se entrega EXP ni col por matar jugadores.</p><div class="race-flags"><label class="check"><input type="checkbox" [(ngModel)]="rules.enabled"> Permitir PvP</label><label class="check"><input type="checkbox" [(ngModel)]="rules.selfDefense"> Respetar defensa propia</label><label class="check"><input type="checkbox" [(ngModel)]="rules.penalizeMurdererKills"> Penalizar también matar asesinos sin defensa propia</label></div>
<div class="effect-fields">@for(f of fields;track f.id){<label>{{f.name}}<input type="number" [step]="f.step||1" [(ngModel)]="rules[f.id]"></label>}</div>
<p class="muted">La marca de asesino dura el tiempo configurado y continúa si la ciudadanía queda bajo el umbral. Desconectarse deja el personaje expuesto hasta terminar el combate. El botón PvP permite atacar; no concede inmunidad.</p></section>}`})
export class PvpConfigComponent{
 @Input() rules:any;
 fields=[{id:'minLevel',name:'Nivel mínimo'},{id:'initialCitizenship',name:'Ciudadanía inicial'},{id:'minCitizenship',name:'Ciudadanía mínima'},{id:'maxCitizenship',name:'Ciudadanía máxima'},{id:'murderPenalty',name:'Puntos perdidos por asesinato'},{id:'murdererThreshold',name:'Umbral de asesino (≤)'},{id:'murdererSeconds',name:'Marca de asesino (s)'},{id:'aggressionSeconds',name:'Defensa propia / agresión (s)'},{id:'combatSeconds',name:'Combate tras último golpe (s)'},{id:'spawnProtectionSeconds',name:'Protección al aparecer (s)'},{id:'safeRadius',name:'Radio protegido del refugio',step:.5},{id:'portalSafeRadius',name:'Radio protegido del portal',step:.5},{id:'damageMultiplier',name:'Multiplicador de daño PvP',step:.05},{id:'redemptionCost',name:'Coste de redención (col)'},{id:'redemptionPoints',name:'Ciudadanía por redención'},{id:'redemptionCooldownSeconds',name:'Recarga de redención (s)'}];
}
