import { Component, Input } from '@angular/core';
import { FormsModule } from '@angular/forms';
@Component({selector:'skills-config',standalone:true,imports:[FormsModule],template:`
@if(catalog?.specializations){<section class="editor-card" id="skills-config"><span class="eyebrow gold">ESPECIALIDADES Y HABILIDADES</span><h2>Ramas de combate</h2><p class="muted">La especialidad determina armas, ropa y talentos permitidos. «Asesino» como especialidad no equivale a la marca criminal por PvP.</p>
@for(s of catalog.specializations;track s.id){<details class="config-node"><summary>{{s.name}} · {{s.classId}}</summary><label>Nombre<input [(ngModel)]="s.name"></label><label>Descripción<input [(ngModel)]="s.description"></label><div class="field-row"><label>Armas permitidas<select multiple [(ngModel)]="s.weaponKinds">@for(k of weapons;track k){<option [value]="k">{{k}}</option>}</select></label><label>Armaduras permitidas<select multiple [(ngModel)]="s.armorStyles">@for(k of armors;track k){<option [value]="k">{{k}}</option>}</select></label></div><div class="effect-fields">@for(e of effects;track e.id){<label>{{e.name}}<input type="number" step=".1" [ngModel]="s.effects[e.id]||0" (ngModelChange)="s.effects[e.id]=$event"></label>}</div></details>}
<header class="binding-heading"><h3>Habilidades activas ({{catalog.skills.length}})</h3><button (click)="add()">+ Añadir habilidad</button></header>
<label>Habilidad<select aria-label="Habilidad a editar" [(ngModel)]="index">@for(s of catalog.skills;track s.id;let i=$index){<option [ngValue]="i">{{s.name}} · {{s.classId}}</option>}</select></label>
@if(skill();as s){<div class="field-row"><label>Nombre<input [(ngModel)]="s.name"></label><label>Clase<select [(ngModel)]="s.classId" (ngModelChange)="classChanged()">@for(c of catalog.classes;track c.id){<option [value]="c.id">{{c.name}}</option>}</select></label></div><label>Descripción<input [(ngModel)]="s.description"></label><div class="field-row"><label>Especialidades (vacío: todas)<select multiple [(ngModel)]="s.specializationIds">@for(p of specs(s.classId);track p.id){<option [value]="p.id">{{p.name}}</option>}</select></label><label>Talento que la desbloquea<select [(ngModel)]="s.talentId">@for(t of talents(s.classId);track t.id){<option [value]="t.id">{{t.name}} · {{t.branch}}</option>}</select></label></div><div class="field-row"><label>Efecto<select [(ngModel)]="s.kind"><option value="damage">Daño directo</option><option value="curse">Maldición</option><option value="heal">Curación</option><option value="buff">Mejora</option><option value="summon">Invocación PvE</option><option value="taunt">Provocación PvE</option></select></label><label>Elemento<select [(ngModel)]="s.element">@for(e of elements;track e){<option [value]="e">{{e}}</option>}</select></label></div>
<div class="effect-fields">@for(f of fields;track f.id){<label>{{f.name}}<input type="number" step=".1" [(ngModel)]="s[f.id]"></label>}</div><p class="muted">Daño directo: potencia × daño del personaje. Maldición: potencia de daño por segundo y efectos temporales. Curación: potencia en PV. Invocación: daño base del aliado. Un radio mayor de cero afecta un área.</p><div class="effect-fields">@for(e of effects;track e.id){<label>{{e.name}} temporal<input type="number" step=".1" [ngModel]="s.effects[e.id]||0" (ngModelChange)="s.effects[e.id]=$event"></label>}</div><button (click)="catalog.skills.splice(index,1);index=0">Eliminar habilidad</button>}
</section>}`})
export class SkillsConfigComponent{
 @Input() catalog:any;index=0;weapons=['sword','dagger','greatsword','staff','wand','shield','orb','tome'];armors=['tunic','leather','mail','plate'];elements=['physical','fire','ice','water','earth','light','shadow','specialization'];
 effects=[{id:'maxHp',name:'PV'},{id:'damage',name:'Daño'},{id:'defense',name:'Defensa'},{id:'speed',name:'Velocidad'},{id:'criticalChance',name:'Crítico (%)'},{id:'healing',name:'Curación'},{id:'skillPower',name:'Potencia de habilidad'},{id:'cooldownReduction',name:'Reducción recarga'}];fields=[{id:'power',name:'Potencia'},{id:'range',name:'Alcance'},{id:'radius',name:'Radio de área'},{id:'duration',name:'Duración (s)'},{id:'cooldown',name:'Recarga (s)'}];
 skill(){return this.catalog?.skills[this.index];}specs(id:string){return this.catalog.specializations.filter((s:any)=>s.classId===id);}talents(id:string){return this.catalog.progression.talents.filter((t:any)=>t.classId===id);}
 classChanged(){this.skill().specializationIds=[];this.skill().talentId=this.talents(this.skill().classId)[0]?.id||'';}
 add(){const s=this.skill()?structuredClone(this.skill()):{classId:this.catalog.classes[0].id,description:'Define el efecto.',specializationIds:[],talentId:this.catalog.progression.talents[0]?.id||'',kind:'damage',element:'physical',power:1,range:3,radius:0,duration:0,cooldown:10,effects:{}};s.id='skill-'+crypto.randomUUID().slice(0,8);s.name='Nueva habilidad';this.catalog.skills.push(s);this.index=this.catalog.skills.length-1;}
}
