import {Component,Input} from '@angular/core';
import {FormsModule} from '@angular/forms';
@Component({selector:'training-config',standalone:true,imports:[FormsModule],template:`
<section class="editor-card training-config"><span class="eyebrow gold">PRÁCTICA · SIN RECOMPENSAS</span><h2>Zona de entrenamiento</h2>
@if(!floor.training){<p>Este piso no tiene patio. Añade uno y ajusta su posición antes de guardar.</p><button (click)="create()">Añadir zona de entrenamiento</button>}
@else{<p class="muted">Zona protegida del PvP y de ataques de criaturas. Los muñecos mantienen las recargas y el alcance reales de cada habilidad.</p><label>Nombre del patio<input [(ngModel)]="floor.training.name"></label><div class="field-row"><label>Centro X<input type="number" [(ngModel)]="floor.training.x"></label><label>Centro Z<input type="number" [(ngModel)]="floor.training.z"></label><label>Radio<input type="number" min="3" max="12" [(ngModel)]="floor.training.radius"></label></div><div class="field-row"><label>Reposición tras inactividad (s)<input type="number" min="1" max="60" [(ngModel)]="floor.training.recoverySeconds"></label><label>Nueva sesión tras pausa (s)<input type="number" min="5" max="300" [(ngModel)]="floor.training.sessionResetSeconds"></label></div>
<div class="table-scroll"><table><thead><tr><th>Nombre</th><th>X</th><th>Z</th><th>PV</th><th>Defensa</th><th>Aliado</th><th></th></tr></thead><tbody>@for(d of floor.training.dummies;track d.id;let i=$index){<tr><td><input [(ngModel)]="d.name" aria-label="Nombre del muñeco"></td><td><input type="number" [(ngModel)]="d.x" aria-label="Muñeco X"></td><td><input type="number" [(ngModel)]="d.z" aria-label="Muñeco Z"></td><td><input type="number" min="100" max="100000" [(ngModel)]="d.maxHp" aria-label="PV del muñeco"></td><td><input type="number" min="0" max="100" [(ngModel)]="d.defense" aria-label="Defensa del muñeco"></td><td><input type="checkbox" [(ngModel)]="d.ally" aria-label="Muñeco aliado"></td><td><button (click)="floor.training.dummies.splice(i,1)" aria-label="Eliminar muñeco">×</button></td></tr>}</tbody></table></div><button (click)="add()" [disabled]="floor.training.dummies.length>=20">Añadir muñeco</button><button (click)="floor.training=null">Retirar zona de entrenamiento</button><p class="muted">Separa los muñecos al menos 1,5 m y colócalos a 1 m del borde. El aliado vuelve al 50 % de vida para repetir pruebas de curación.</p>}
</section>`})
export class TrainingConfigComponent {
 @Input() floor:any;
 create(){this.floor.training={name:'Patio de entrenamiento',x:this.floor.spawn.x,z:this.floor.spawn.z,radius:5,recoverySeconds:5,sessionResetSeconds:15,dummies:[]};this.add();}
 add(){const z=this.floor.training;z.dummies.push({id:'dummy-'+crypto.randomUUID().slice(0,8),name:'Nuevo muñeco',x:z.x,z:z.z,maxHp:5000,defense:0,ally:false});}
}
