package dev.aincrad;
import java.util.*;

public final class Skills {
 public record Skill(String id,String classId,String name,String description,List<String> specializationIds,String talentId,String kind,String element,double power,double range,double radius,double duration,double cooldown,Map<String,Double> effects){}
 public static class State {public Map<String,Long> readyAt=new LinkedHashMap<>();public List<String> slots=new ArrayList<>(List.of("","","",""));public State copy(){var s=new State();s.readyAt.putAll(readyAt);s.slots=new ArrayList<>(slots);return s;}}
 public static class Active {public String source,id,name;public Map<String,Double> effects;public long expires,nextTick;public double damage;Active(String source,Skill s,long now){this.source=source;id=s.id();name=s.name();effects=Map.copyOf(s.effects());expires=now+(long)(s.duration()*1000);nextTick=now+1000;damage=s.kind().equals("curse")?s.power():0;}}
 public static boolean learned(GameWorld.Player p,Skill s){return s.classId().equals(p.appearance.classId())&&Specializations.permits(s.specializationIds(),p.appearance.specializationId())&&p.talentRanks.getOrDefault(s.talentId(),0)>0;}
 public static void validate(WorldData.CharacterOptions c){if(c.skills==null||c.skills.size()>200)throw new IllegalArgumentException("Catálogo de habilidades inválido");Set<String> ids=new HashSet<>();for(var s:c.skills){if(s==null||!Progression.id(s.id())||!ids.add(s.id())||!Progression.text(s.name(),80)||!Progression.text(s.description(),600)||s.kind()==null||!Set.of("damage","curse","heal","buff","summon","taunt").contains(s.kind())||s.element()==null||!Set.of("physical","fire","ice","water","earth","light","shadow","specialization").contains(s.element())||!Double.isFinite(s.power())||s.power()<0||s.power()>250||!Double.isFinite(s.range())||s.range()<0||s.range()>15||!Double.isFinite(s.radius())||s.radius()<0||s.radius()>10||!Double.isFinite(s.duration())||s.duration()<0||s.duration()>60||!Double.isFinite(s.cooldown())||s.cooldown()<1||s.cooldown()>300)throw new IllegalArgumentException("Habilidad activa inválida");var t=c.progression.talents.stream().filter(v->v.id().equals(s.talentId())&&v.classId().equals(s.classId())).findFirst().orElseThrow(()->new IllegalArgumentException("La habilidad necesita un talento de su clase"));Specializations.references(s.specializationIds(),s.classId(),c);for(var spec:c.specializations)if(spec.classId().equals(s.classId())&&Specializations.permits(s.specializationIds(),spec.id())&&!Specializations.permits(t.specializationIds(),spec.id()))throw new IllegalArgumentException("Especialidad de habilidad y talento incompatibles");Progression.effects(s.effects());}}
 public static List<String> slots(GameWorld.Player p){var all=p.catalog.skills.stream().filter(s->learned(p,s)).map(Skill::id).toList();var selected=new ArrayList<String>();for(int i=0;i<4;i++){String saved=i<p.skills.slots.size()?p.skills.slots.get(i):"";selected.add(all.contains(saved)&&!selected.contains(saved)?saved:"");}for(int i=0;i<4;i++)if(selected.get(i).isEmpty()){for(String id:all)if(!selected.contains(id)){selected.set(i,id);break;}}return selected;}
 public static Map<String,Object> view(GameWorld.Player p){long now=p.clock.getAsLong();Map<String,Double> cds=new LinkedHashMap<>();p.skills.readyAt.forEach((id,t)->cds.put(id,Math.max(0,(t-now)/1000.0)));return Map.of("learned",p.catalog.skills.stream().filter(s->learned(p,s)).map(Skill::id).toList(),"slots",slots(p),"cooldowns",cds);}
 static double modifier(List<Active> effects,String stat,long now){return effects.stream().filter(a->a.expires>now).mapToDouble(a->a.effects.getOrDefault(stat,0.0)).sum();}
 static List<String> names(List<Active> effects,long now){return effects.stream().filter(a->a.expires>now).map(a->a.name).distinct().toList();}
 static void apply(List<Active> target,GameWorld.Player source,Skill s,long now){target.removeIf(a->a.source.equals(source.id)&&a.id.equals(s.id()));if(target.size()<32)target.add(new Active(source.id,s,now));}
}
